### ISSUE TITLE
Fortius iMagic and Chromebook

### ISSUE THREAD

**Issue by pimdespreeuw** [WouterJD/FortiusANT#109]
Hi Wouter,

My father-in-law gave me his old Tacx Fortius iMagic to continue cycling during the rainy autumn and winter days. Unfortunately, I do not have a Windows laptop, but a Chromebook. Is there a way to start Zwifting on the Fortius using this as well?

Thanks in advance!

Cheers,
Tim

**Comment by WouterJD** [comment]
Q1: How does iMagic c

**Comment by pimdespreeuw** [comment]
Via USB

**Comment by WouterJD** [comment]
Reason i asked is the i- in i-Magic (What does it mean?)

Now: install python on Chromebook with required modules. Also install libusb. And check whether ANRdongle is supported.
Where are you going to run Zwift?

**Comment by WouterJD** [comment]
If it must run all on the Chromebook, you need three USBports

**Comment by pimdespreeuw** [comment]
Sorry, indeed, it is I-Magic (not iMagic).

It's getting quite technical, so I'll have to take some time to figure it all out during the weekend.  

W.r.t. your last question: I intend to use my ipad for Zwift. Will that do the trick?

Thanks already for your help! If there is anything else I should take into account, please let me know :)

**Comment by WouterJD** [comment]
If the iPad supports ANT ... yes it could work

**Comment by WouterJD** [comment]
Any news?
