### ISSUE TITLE
FortiusANT user manual review

### ISSUE THREAD

**Issue by WouterJD** [WouterJD/FortiusANT#110]
Hi all; I published the [Fortius ANT user manual](https://github.com/WouterJD/FortiusANT/blob/master/supportfiles/FortiusANTUserManual.pdf). The wiki is consolidated into the manual and I hope it's helpful for you all. If there are questions, drop them here!
Version information is available in the [Wiki](https://github.com/WouterJD/FortiusANT/wiki)

**Comment by WouterJD** [comment]
No response, so closed.

**Comment by WouterJD** [comment]
Ref experience from Koen: https://github.com/WouterJD/FortiusANT/issues/14#issuecomment-719431648

**Comment by lello72** [comment]
Great work
