### ISSUE TITLE
Latest windows exe deleted by Norton antivirus

### ISSUE THREAD

**Issue by SpeedColumbus** [WouterJD/FortiusANT#136]
When unzipping the latest windows file FortiusANT.exe gets deleted by Norton Antivirus with the warning message: Heur.AdvML.B heuristic virus detected. Is this a false positive?

**Comment by Marmi86** [comment]
I habe the same problem with BullGuard

**Comment by WouterJD** [comment]
That's bad news. On my system, the uploaded FortiusANT.exe does not give errors (Windows 10, Microsoft Defender).

**Comment by WouterJD** [comment]
Hi @Marmi86 and @SpeedColumbus ; welcome in the FortiusANT community. I would appreciate that you introduce yourselves, just for my curiosity what Tacx is used and where you are from

**Comment by SpeedColumbus** [comment]
Hi Wouter, Sure.. My name is Jordy and I live in The Hague, The Netherlands. I have an old Taxc Flow T1901 brake with a T1932 upgraded VR interface (USB). I have tested the FortiusANT file in a sandbox environment without Norton active, 2  Ant+ USB dongles and THEN the GUI works fine and also seems to work great with ZWIFT (I couldn't get Zwift working with the original antifier).

**Comment by WouterJD** [comment]
Hi all; I have verified .exe and no issues at my side. Please verify at your side what's wrong.
