### ISSUE TITLE
Install Fortiusant on Ubuntu 20.04

### ISSUE THREAD

**Issue by Marmi86** [WouterJD/FortiusANT#139]
Hello,
I installed FortusAnt on a fresh Ubuntu 20.04 VM
![image](https://user-images.githubusercontent.com/41163956/98849891-35005880-2454-11eb-8de4-5749015211a6.png)

I followed the installation instructions from the manual,
but at this point I get an error message:

.....
LOC=/lib/modules/uname -r/kernel/drivers/usb/serial/
sudo mv $LOC/usb-serial-simple.ko ~/Documents

![image](https://user-images.githubusercontent.com/41163956/98849405-704e5780-2453-11eb-8e37-40c3e93c4d5a.png)

Open terminal in AntBridge folder
make; make;
sudo make install 

![image](https://user-images.githubusercontent.com/41163956/98849546-ae4b7b80-2453-11eb-8d45-e5266ba3f020.png)

Can someone help me?

Marco

**Comment by mattipee** [comment]
Just looking at face value, in the first LOC= bit, do you need backticks around the uname -r?

**Comment by Marmi86** [comment]
I follow the FortiusAnt manuel steps
