### ISSUE TITLE
No Tacxtrainer found

### ISSUE THREAD

**Issue by Spider39** [WouterJD/FortiusANT#141]
Heb Fortiusant software op de computer staan (Windows 10) als ik de usb van de tacxtrainer aansluit . Wordt de tacxtrainer niet gevonden.
In de GUI onder nummer 6 staat  No Tacx trainer found.

**Comment by WouterJD** [comment]
Heb je libusb geinstalleerd en TTS verwijderd?

PS. Stel je even voor aub, altijd leuk te weten wie FortiusANT gebruikt, met welke trainer en waar je vandaan komt!

**Comment by Spider39** [comment]
Oh Sorry zal me even voorstellen ik ben Hendrik kom uit Friesland . Ik heb een tacx fortius die met een usbkabel is aangesloten. Ik heb een laptop die op windows 10 draait. Ik heb fortiusant er op gezet en ook libusb geïnstalleerd (ik denk dat het daar fout gaat).Op de laptop staat geen tacx software (TTS). #

**Comment by WouterJD** [comment]
Nogmaals welkom, Hendrik!
Heb je libusb geinstalleerd vogens handleiding 3.5.1?

**Comment by Spider39** [comment]
Hallo Wouter.
Heb het nu voorelkaar dat fortiusant software de tacxtrainer heeft gevonden en ook de ant+ dongle gevonden heeft. Nu eens zien of de kalibratie juist verloopt.
Wat een super project .
Tot zover bedankt ik hou jullie op de hoogte.

**Comment by WouterJD** [comment]
@Spider39 top! Succes en ik zie je op strava !
