### ISSUE TITLE
VM Ubuntu+ FortiusAnt

### ISSUE THREAD

**Issue by Marmi86** [WouterJD/FortiusANT#142]
Hello everyone,
does anyone use FortiusAnt in a VM (Ubuntu) and can they provide it to me?

Hallo zusammen,
benutz jemand FortiusAnt in einer VM und kann mir diese zur Verfügung stellen?

**Comment by WouterJD** [comment]
Hi Marco, perhaps you can described your issue so we can think with you to resolve.

**Comment by WouterJD** [comment]
No info received
