### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by brunomvgirard** [WouterJD/FortiusANT#145]
I'm installing FortiusAnt on my PC. First I've installed Python 3,7,9. Installation is OK and PATH to. Try to following instruction :
pip install -r requirements.txt
I get these errors : 
ERROR: Could not find a version that satisfies the requirement json (from -r requirements.txt (line 1)) (from version : none)
ERROR: No matching distribution found for json (from -r requirements.txt (line 1))

How can I solve these errors? Thank you

**Comment by WouterJD** [comment]
Welcome to the FortiusANT community
--
I'm always curious to know who I communicate with, where FortiusANT is used and what configuration is used.
Please tell me what bundle did you buy, and what brake and what head unit do you use?
I would therefore appreciate that you introduce yourself; perhaps leave a comment under issue #14.
--
json should not have been in requirements.txt; it's removed.
Please try again
