### ISSUE TITLE
Strava Fortius-ANT club now operational

### ISSUE THREAD

**Issue by Muleguy-Security** [WouterJD/FortiusANT#174]
Folks,
Just to make it easier for us to share rides, test rides, etc. with contributors I have created a Strava Club. It can be accessed via the following link: [[https://www.strava.com/clubs/fortius-ant](https://www.strava.com/clubs/fortius-ant)]. Membership is open and should be automatic. Will dress it up with some graphics shortly. 

I hope this helps in the development of this great tool!

- Hugh

**Comment by WouterJD** [comment]
👍 thanks

**Comment by marcoveeneman** [comment]
As an exercise i created a badge for the FortiusANT Strava club, see #177
