### ISSUE TITLE
Undefined `legacyResistance2Power`

### ISSUE THREAD

**Issue by fritz-hh** [WouterJD/FortiusANT#19]
The function `legacyResistance2Power`.
It should be replaced by `legacyResistance2Power` as the latter function supports both the new and the legacy protocols.

**Comment by fritz-hh** [comment]
I will provide a PR

**Comment by WouterJD** [comment]
The main advantage for compiled languages: to find this kind of typo's.
I first created two functions, but it proved to be easier to use the current implementation where both conversion functions support both interfaces.

**Comment by fritz-hh** [comment]
In fact I am quite impressed by the few issues I had to correct, considering that you don't have an imagic device!
