### ISSUE TITLE
External Cadence Sensor

### ISSUE THREAD

**Issue by rcerrie** [WouterJD/FortiusANT#209]
I would like to know if a external ANT+ cadence sensor can be used instead of the factory (magnet) one? If so how do I enable it so Fortius Ant pick it up?

**Comment by WouterJD** [comment]
FortiusAnt use the cadence sensor quite passively; only passing it to the FE-C interface and displaying it on the screen.
Your Fortius/T1932 willl not work without the magnetic factory cadense sensor, though.

Please explain some background.

**Comment by rcerrie** [comment]
Thanks. Was just thinking about it since I got ordered a cadence sensor for my mountain bike.

**Comment by WouterJD** [comment]
See manual paragraph 5.6; I have added some additional text for next upload.
