### ISSUE TITLE
Power not ajusted with slope in Zwift 

### ISSUE THREAD

**Issue by Virgile28** [WouterJD/FortiusANT#213]
Hi,

First of all thanks for the solution that you have proposed, it's really great !

I'm french rider and I have a problem with the resistance which is not adjusted with the slope in Zwift. I run the FortiusANT exe, all is detected, I launched the calibration during 30 sec at 20 km/h, that's ok. Then I connect on Zwift and start to pedal, the cyclist is moving. But the resistance seems not to correspond with the slope. In fact the resistance is low during 5 sec then strong during 3 sec then slow during 5 sec and strong during 3 sec etc. Do I have to to pass some arguments in enter of the command line ? If it is the case, how do we proceed because I don't understand in the manual. 

Thanks in advance for your responses,

Best regards,

Virgile

**Comment by WouterJD** [comment]
Hi @Virgile28 
Welcome to the FortiusANT community
- - -
I'm always curious to know who I communicate with, where FortiusANT is used and what configuration is used.
Please tell me what bundle did you buy, and what brake and what head unit do you use?
I would therefore appreciate that you introduce yourself; perhaps leave a comment under issue #14.
- - -
What you could do is send a logfile as created with the -d127 flag on the command line.

**Comment by switchabl** [comment]
@Virgile28 I assume you are using a Fortius? This sounds like the magnetic cadence sensor is maybe not connected properly? The brake will shut-down after a few seconds if there is no cadence signal.

**Comment by k4r1vince** [comment]
Hi @Virgile28 I seem to be having the exact same issue. As @switchabl suggested that seems to be the problem but i've tried new batteries in the sensor and it isn't solving it. I know this is no help but sort of hijacking the thread as im having the same issue.

**Comment by WouterJD** [comment]
If you have a Fortius there is no battery but hard wired; please add foto of you config

**Comment by k4r1vince** [comment]
![20210121_182051](https://user-images.githubusercontent.com/77455352/105394764-e4f0ff80-5c15-11eb-8c64-92cf9d71f2fe.jpg)
Hi @WouterJD The sensor on the crank has a battery, the other part is hard wired, can't see any damage to the wire or connections

**Comment by switchabl** [comment]
@k4r1vince The part on the crank looks like an ANT+ cadence sensor (Garmin?). For the Fortius sensor to work, you need a magnet on crank instead (this is the original part: https://www.xxcycle.com/marques/tacx/images/large/27145.jpg)

**Comment by k4r1vince** [comment]
Hi @switchabl thats right, the sensor is Garmin, I thought the seller sold me the trainer with this sensor as the other sensor wasn't there, do you know where or what I could use as a replacement?

Thanks
Karl

**Comment by k4r1vince** [comment]
Do you think this would work? @switchabl 

https://www.amazon.co.uk/dp/B001IKK2CC/ref=cm_sw_r_cp_apa_fabc_G7CcGbGCZHED3?_encoding=UTF8&psc=1

**Comment by switchabl** [comment]
The original part number is T1603, but that may not be available anymore. The sensor is a simple magnetic switch. In a pinch, I think more or less any magnet that you can somehow fit on your crank arm (facing the sensor) should work. You can search for "cadence magnet".

**Comment by WouterJD** [comment]
![image](https://user-images.githubusercontent.com/47486941/105425096-fe5f6f00-5c48-11eb-897b-d59185cac520.png)

Question: what is the cable I see, I cannot see it for 100%
It looks like the cable and the FortiusSensor

This is what I would expect (my bike):
![image](https://user-images.githubusercontent.com/47486941/105425221-3666b200-5c49-11eb-8c98-72a199c38a48.png)

Reference to Tacx: https://tacx.com/nl/product/cadence-sensor-i-flow-and-fortius/
![image](https://user-images.githubusercontent.com/47486941/105425322-70d04f00-5c49-11eb-80dc-aa005c8df24d.png)

**Comment by k4r1vince** [comment]
Hi @WouterJD & @switchabl the magnet from Amazon works perfect. Finally got a ride in! 

@Virgile28 have you got the cable sensor and magnet? I was having the exact same issue as you but I didn't have a magnet.

Thanks

Karl

**Comment by Virgile28** [comment]
Hi,
Thank you for your answers which allowed me to solve the problem. In fact I didn't connect de cadence sensor because I thought it wasn't necessary for the FortiusANT to function. And the rear wheel wasn't properly placed on the roller so the FortiusANT could'nt do good calibration.
Now the FortiusANT is working fine and I can zwift, it's very great ! Originally my problem was that I could'nt use my Fortius because the TTS3 was no longer updated with my Fortius so I figured I couldn't use the Fortius anymore. So many thanks @WouterJD for the python program, it permits me to use my Fortius ! It's awesome to find some python code on the internet that makes your home-trainer work !
