### ISSUE TITLE
Problems with high inclines

### ISSUE THREAD

**Issue by arto2703** [WouterJD/FortiusANT#214]
Hallo, we need help. By courses featured with an incline of 12% or more, the brake gets out of work, no resistance. Thanks for help.

**Comment by WouterJD** [comment]
Hi @arto2703 
Welcome to the FortiusANT community
- - -
I'm always curious to know who I communicate with, where FortiusANT is used and what configuration is used.
Please tell me what bundle did you buy, and what brake and what head unit do you use?
I would therefore appreciate that you introduce yourself; perhaps leave a comment under issue #14.
- - -

It would ceertainly help if would tell what trainer you use!

**Comment by WouterJD** [comment]
No info received
