### ISSUE TITLE
Flat resistance on magnetic brake at low wheel speed

### ISSUE THREAD

**Issue by WouterJD** [WouterJD/FortiusANT#223]
@bikebeppe64 has a T1932 headunit and a T1901 brake

FortiusAnt 5.1 reports:
```
16:29:50,303: Motor Brake Unit Firmware=0x1902 Serial=0 MotorBrake=False
16:29:50,428: FortiusAnt applies the MagneticBrake power curve
```

A ride is done, using Rouvy, and attached files are provided for analysis.
[FortiusAnt_CCS - Bormio FA 51VI_TEST.log](https://github.com/WouterJD/FortiusANT/files/5872796/FortiusAnt_CCS.-.Bormio.FA.51VI_TEST.log)
[FortiusAntGUI_CCS - Bormio FA 51VI_TEST.log](https://github.com/WouterJD/FortiusANT/files/5872798/FortiusAntGUI_CCS.-.Bormio.FA.51VI_TEST.log)
[Rouvy_CCS - Bormio PWR Meter_TEST.tcx.txt (rename back)](https://github.com/WouterJD/FortiusANT/files/5872805/Rouvy_CCS.-.Bormio.PWR.Meter_TEST.tcx.txt)
[FortiusAnt_CCS - Bormio FA 51VI_TEST.json.txt (rename back)](https://github.com/WouterJD/FortiusANT/files/5872806/FortiusAnt_CCS.-.Bormio.FA.51VI_TEST.json.txt)

**Comment by WouterJD** [comment]
The TCX file is from the Garmin Powermeter; json and logfiles are from FortiusAnt.
Combined together it provides the following image:
![image](https://user-images.githubusercontent.com/47486941/105834542-eaaa6480-5fca-11eb-8440-0b99f5b42d44.png)

**Comment by WouterJD** [comment]
Explanation:
Input:
[1] TargetGrade as provided by Rouvy (multiplied by 100 for scaling purpose)
[2] SpeedKmh (the speed of the bicycle wheel) = speed of the brake roller
Calculated:
[3] TargetPower
[4] TargetResistance (divided by 10 for scaling purpose)
Obtained from brake/headunit:
[5] CurrentResistance
Calculated:
[6] CurrentPower
Obtained from Garmin powermeter:
tcxWatts

**Comment by WouterJD** [comment]
### Displayed Power

Observation: the tcxWatts (power meter) and CurrentPower (FortiusAnt and Rouvy display) curves nicely match; there seems to be a constant factor.
The -p command-line option can be used to adjust this.

**Comment by switchabl** [comment]
The brake resistance seems to be maxed out most of the time. From the data, it looks like the rolling resistance is significantly lower than what is set. So instead of changing -p, I suggest either
- adjusting down -c or
- increasing the roller pressure with the adjustment knob (preferred, as it actually increases max resistance)
until the displayed power matches. I guess it shows the need for a proper calibration routine again.

The brake was sold as "6% max" I believe, but unfortunately the actual limit may be ever lower depending on rider weight, wheel speed and roller pressure. Decreasing the grade factor -G may give a better (more dynamic) ride feeling.

**Comment by WouterJD** [comment]
### TargetResistance

The TargetResistance appears to be quite flat.
The WheelSpeed is around 10 km/hr
The -G parameter is NOT specified
And Rouvy is used as an application

This causes the following: Rouvy transmits a slope-percentage which results in TargetPower. Since this power is quite high (compared to the athlete) the speed will be low and -to achieve the power- the resistance is high.

If the wheel-speed would be *2 the curve would be as shown below ([4]TargetResistanceVBA(s*2)/10), which follows the grade-curve:
![image](https://user-images.githubusercontent.com/47486941/105840398-437dfb00-5fd3-11eb-8b33-634ad4b6706a.png)

**Comment by WouterJD** [comment]
### Recommendation

FortiusAnt -p80 -G50

- -p Adjusts the displayed power so that it better matches the Garmin Powermeter
- -G adjusts the requested grade from Rouvy and enables a higher wheelspeed, making the trainer more flexible

**Comment by WouterJD** [comment]
### Performance finetuning recommendation

> The brake was sold as "6% max" I believe, but unfortunately the actual limit may be even lower depending on rider weight, wheel speed and roller pressure. Decreasing the grade factor -G may give a better (more dynamic) ride feeling.

@switchabl I fully agree

@bikebeppe64 You can do a lot on performance finetuning and I hope this issue helps you to understand.
- Check the runoff time; the brake should not be too tight/too loose
- -G adjusts the requested grade from Rouvy and enables a higher wheelspeed, making the trainer more flexible
- -c to adjust the powercurve as described by @switchabl so that it better matches the Garmin Powermeter
- -p As last adjustment of the reported power

**Comment by WouterJD** [comment]
This is the excel sheet for reference.
[FortiusANT JSON Analysis.xlsx](https://github.com/WouterJD/FortiusANT/files/5873077/FortiusANT.JSON.Analysis.xlsx)

**Comment by BikeBeppe64** [comment]
Done a new test today and it's real more than acceptable for a big hill 
Rouvy : Teglio Climb 9/22%
-c13 virtual gear 50/50 real gear 50/15 (+/-) cadence 55~70

**Comment by WouterJD** [comment]
Great news; happy rides!

**Comment by WouterJD** [comment]
Added to manual
