### ISSUE TITLE
5.1+4.2 quality upgrade working brilliantly with Fortius T1932 and Golden Cheetah

### ISSUE THREAD

**Issue by pcuttriss** [WouterJD/FortiusANT#231]
Hi Wouter

Not an issue but I wanted to recognise the excellent work you have done and provide a setup that others may find useful.

Running on Windows 10

The hardware in use is as follows:
Tacx Trainer T1932
Motor Brake Unit Firmware=0x1007 Serial= 6639 year=2010 type=T1941 Version2=3086 MotorBrake=True

I am also using the development version of Golden Cheetah and selecting the FEC trainer presented by FortiusAnt

One of the issues I had was adjusting the power (which you kindly solved in #210). With the new feature in 5.1 of the virtual gears I now have a working setup where I can fine tune the power reflected by the brake as it changes during the session (this is something that the brake I have has always done....power changes through the session, sometimes quite a lot).

Basically I use the virtual gearing to do the fine adjustment during the session and I leave Golden Cheetah to adjust the actual power rates for the session.

I start FortiusAnt with the following options (the HRM is really optional..... -H0 works just as well). The power difference between the value recorded from the brake and the powertap hub in use is adjusted at a macro level using '-p135' and I have tightened up the mid range virtual gearing so that I have fine granularity changes between 17 and 21 teeth on the rear cassette. This is adjusted using the '-T34-50*x30-27-25-23-21-20-19*-18-17-15-13' option.

Details of the shortcut (call the downloaded .exe whatever you want):
C:\Users\Paul\Downloads\FortiusANT-5.1.exe -n -g -a -H10030 -p135 -T34-50*x30-27-25-23-21-20-19*-18-17-15-13

This now means that I can finely adjust the power difference to stay within a few watts of the Golden Cheetah profile throughout the ride. While this is not a show stopper for folk using GC it does mean you don't get the GC interface colouring your power output because you are higher/lower than the specified rate.

Absolutely fantastic job and it's a huge help in me maintaining my fitness for a return to Brazilian Jiu Jitsu in the coming months. And it has given the Fortius a huge new lease of life :-)

Dankjewel.

Paul C

**Comment by WouterJD** [comment]
Added to manual
