### ISSUE TITLE
Start Up on Mac

### ISSUE THREAD

**Issue by danlewis97** [WouterJD/FortiusANT#233]
Hi,

I have a Tacx Vortex and I am using Mac. I have followed Manual until I got to the FortiusAnt Start Up section. I cannot code this to start. I cannot open any Start Up file due to them being .bat and manually typing them in Terminal doesn't appear to work saying 'command not found'.

Any ideas Mac users?

**Comment by WouterJD** [comment]
HI @danlewis97 
Welcome to the FortiusANT community
- - -
I'm always curious to know who I communicate with, where FortiusANT is used and what configuration is used.
Please tell me what bundle did you buy, and what brake and what head unit do you use?
I would therefore appreciate that you introduce yourself; perhaps leave a comment under issue #14.
- - -

**Comment by WouterJD** [comment]
Who provides a good Mac-quote how to start a program on the mac; I will add to the manual in a next version.

**Comment by marcoveeneman** [comment]
I'm using a mac and 'just' start it as follows on the command line.
`python3 FortiusAnt.py -a -b -g`

Note that you need to navigate on the command line to the `<your FortiusAnt directory>/pythoncode` location

**Comment by WouterJD** [comment]
Some notes added to manual
