### ISSUE TITLE
Can't connect the device

### ISSUE THREAD

**Issue by meiki1** [WouterJD/FortiusANT#236]
I have tried to connect the role with Zwift.
I can control the role manually in your program (Fortius ANT), but when I want to connect it in Zwift, it does not find anything. No matter what I select. I have read through the other problem cases but came up with no solution. Have also specially fetched the Garmin ANT stick. Have it now tried for several days / weeks, unfortunately unsuccessful. Can you help?
Thanks for your support

![grafik](https://user-images.githubusercontent.com/46975579/106663526-1d90c180-65a4-11eb-98a4-26bfc81f8279.png)

![grafik](https://user-images.githubusercontent.com/46975579/106663577-3305eb80-65a4-11eb-8bb5-59e2b81a8e99.png)
![grafik](https://user-images.githubusercontent.com/46975579/106663646-4add6f80-65a4-11eb-9eee-afa22aab5b29.png)
![grafik](https://user-images.githubusercontent.com/46975579/106663693-5d57a900-65a4-11eb-950a-9b623b98d72f.png)

**Comment by TacxBiker** [comment]
Hi,

Do you have only 1 ANT dongle? If you want to use Fortius ANT on 1 computer using ANT you will need 2 ANT dongles.

**Comment by WouterJD** [comment]
Hi @meiki1 
Welcome to the FortiusANT community
- - -
I'm always curious to know who I communicate with, where FortiusANT is used and what configuration is used.
Please tell me what bundle did you buy, and what brake and what head unit do you use?
I would therefore appreciate that you introduce yourself; perhaps leave a comment under issue #14.
- - -

**Comment by meiki1** [comment]
That was the clue I had missed. I thought the Tacx Fortius is ANT source 1 and the stick the second source. With a second stick it helped thanks.
Thanks also for the cool program and support. btw I am from Germany near Cologne
