### ISSUE TITLE
HTTPConnectionPool(host='localhost', port=9999

### ISSUE THREAD

**Issue by harrykl** [WouterJD/FortiusANT#253]
Hello,
if I start FortiusAnt on my MAC I become the Error
.. requests.post() error HTTPConnectionPool(host='localhost', port=9999): Max retries exceeded with url: /ant (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa09bdb5d00>: Failed to establish a new connection: [Errno 61] Connection refused'))

I did not found anything that resolves the problem

Greetings
Harry

**Comment by harrykl** [comment]
With the Installation instructions Raspberry - Bluetooth now it works with Zwift. Tacx connect does not work but it ist godd enough for me.
I had to do: After installing node to the system, you have to set it up for FortiusANT

$ cd ~/FortiusANT/node/
$ npm install

**Comment by WouterJD** [comment]
Hi @harrykl sorry for being quite late; I think the npm install command was overlooked - I think it was in the manual already (I am reviewing the manual and do not have older versions at hand)
