### ISSUE TITLE
Single sponsorship payment

### ISSUE THREAD

**Issue by Mickyduck55** [WouterJD/FortiusANT#263]
Wouter please delete after you have read this ;) Done :-)

**Comment by WouterJD** [comment]
Hi @Mickyduck55 
YOu could ping me on facebook messenger with your question.

**Comment by WouterJD** [comment]
Currently github sponsorship is monthly and I did not find an option to enable a Single sponsorship.

**Comment by Mickyduck55** [comment]
Thank you

**Comment by WouterJD** [comment]
Hi @Mickyduck55 just let me know how you like to contact

**Comment by WouterJD** [comment]
I have added following remark to the [sponsoring page](https://github.com/sponsors/WouterJD):
- - -
PS. Github does not provide one-time sponsoring.
If you would prefer that option, you can find me on paypal; "Wouter Dubbeldam"

**Comment by Mickyduck55** [comment]
Thank you
