### ISSUE TITLE
Snelheid FortiusAnt niet gelijk aan Zwift 

### ISSUE THREAD

**Issue by BikerVibor** [WouterJD/FortiusANT#266]
Hoi,
Sorry voor NL, Engels niet echt in thuis.
Ik heb alles mooi aan de praat, maar als ik volgens de FortiusAnt 25 km/u rij, maakt Zwift daar 15 km/u van, ben er nog niet achter hoe ik dat kan synchroniseren. Hoe kan ik dat aanpassen?
Het fietsen gaat ook nogal schokkerig.
Setup:
Beone op Fortius, via USB op 1 PC met 2 BT/ANT modules. 

Het vermogen en de cadans komen wel overeen met elkaar.

![zwift-fortiusAnt](https://user-images.githubusercontent.com/78826403/109034877-60881580-76c8-11eb-8c7c-d2bd5e336319.png)

2e  screenshot:

![_Zwift](https://user-images.githubusercontent.com/78826403/109060193-68a27e00-76e5-11eb-9bd5-82c8a2fcd7d9.png)

**Comment by WouterJD** [comment]
Hoi @BikerVibor 
Welkom in de FortiusANT community
- - -
Ik ben altijd nieuwsgierig met wie ik communiceer, waar FortiusANT wordt gebruikt en in welke configuratie.
Welke bundle heb je gekocht, en welke rem en head-unit gebruik je?
Vertel meer over jezelf, eventueel onder issue #14.
- - -

**Comment by WouterJD** [comment]
Zwift en FortiusANT zullen hetzelfde vermogen tonen.
FortiusANT toont de snelheid van het wiel
Zwift rekent de snelheid uit op basis van vermogen en gewicht / helling van de route.

Deze twee snelheden zijn niet gelijk

**Comment by BikerVibor** [comment]
Hoi Wouter,
Sorry, ik dacht dat ik mijzelf al op de kaart gezet had. Maar vast een missertje gehad met opslaan of zoiets. Alsnog gedaan.

Leuk programma FortiusAnt, kost wel wat moeite om je er in in te leven, maar dat gaat steeds beter. 
De afwijking in snelheid is wel erg groot met Zwift. Ik ga eens wat spelen met de instellingen in Zwift en andere trainigsprogramma's proberen.

Grt. Vincent

**Comment by WouterJD** [comment]
Speed in Zwift and FortiusAnt will never be equal, due to different meaning.
