### ISSUE TITLE
BKool does not pair with FortiusANT

### ISSUE THREAD

**Issue by WilburBear** [WouterJD/FortiusANT#267]
I am running a set up with Bluetooth initially on zwift.  Wanted to try BKool but it cant pair to me windows PC.  I only have free subscription but doubt that's the issue.

I know BKOOL isn't on the list of target platforms - is my issue because BKOOL isn't compatible?

**Comment by WilburBear** [comment]
As an additional note - upgraded to v5.2 and also tried BKOOL on a different (more powerful) win10 PC, same result, although as an additional point, I am able to connect and read heart rate from FortiusAnt, I start it with gui, autostart, BLE, d, s

**Comment by WilburBear** [comment]
Logged a ticket with BKool - but no real help (suggested I go through pairing process etc....)  Does anyone have experience with BKool or is it just the case its not compatible?

**Comment by switchabl** [comment]
@WilburBear The BLE protocol (FTMS) is standardized so it _should_ work even if it not explicitly listed. It is however possible that no one has tried that combination (BKool + BLE) and there is some bug there. Unfortunately I don't have a working Bluetooth setup right now so I can't try myself.

**Comment by WilburBear** [comment]
I tried a few other things:

BKool running on laptop with built-in BLE 
Upgrade to premium subscription

Neither of these made any difference.  In all cases FortiusANT heartrate is able to pair but nothing else 

I have paired BKOOL with my sperate heartrate and speed cadence sensors also...

**Comment by WouterJD** [comment]
@WilburBear 
Welcome to the FortiusANT community
- - -
I'm always curious to know who I communicate with, where FortiusANT is used and what configuration is used.
Please tell me what bundle did you buy, and what brake and what head unit do you use?
I would therefore appreciate that you introduce yourself; perhaps leave a comment under issue #14.
- - -

Easiest way to debug: install Trainer Road or Zwift on your phone with trial account and try to pair. TR and Zwift have quite advanced pairing pages that are known working well.

**Comment by WouterJD** [comment]
No additional info received

**Comment by taylor42788** [comment]
I have a running setup of FortiusAnt 5.2 that works with Zwift with ANT+.
I've tried today to install BKool and to connect BKool with FortiusAnt as "SmartTrainer" with ANT+.
After some retries, it finally seem to connect but seem to disconnect right after & the setup is not working.
I've scrolled the logs but did not see any error/warning reported.
Any clue?
Thanks
