### ISSUE TITLE
Raspberry works as Smartphone/TV interface

### ISSUE THREAD

**Issue by decodeais** [WouterJD/FortiusANT#277]
I wanted to test BLE on the RPi4, but this was only available on my smartphone. I needed a larger display. I found am old TV with HDMI input and connected it to my smartphone via RPi4.  This little thing is strong enough to manage FortiusANT and streaming at the sane time!!
I installed srcpy on it and it worked with very low latency. No app on the smartphone needed . You have only to enable the Developers options (USB debuggin)and connect it to the USB-port of the RPi4.
https://snapcraft.io/install/scrcpy/raspbian
I had to start the adb-server on the Raspi first.

`adb start-server`
`scrcpy --max-size 1440`

**Comment by WouterJD** [comment]
I think I miss your point, please provide a picture and some more info.

**Comment by MeanHat** [comment]
@decodeais - I too run FortiusAnt on a RPi linked via Bluetooth to a smartphone (Android - Google Pixel) running Zwift viewed on a TV. Rather than an HDMI connection I cast the screen using a Chromecast on the back of the TV.

**Comment by BikeBeppe64** [comment]
> I wanted to test BLE on the RPi4, but this was only available on my smartphone. I needed a larger display. I found am old TV with HDMI input and connected it to my smartphone via RPi4.  This little thing is strong enough to manage FortiusANT and streaming at the sane time!!
> I installed srcpy on it and it worked with very low latency. No app on the smartphone needed . You have only to enable the Developers options (USB debuggin)and connect it to the USB-port of the RPi4.
> https://snapcraft.io/install/scrcpy/raspbian
> I had to start the adb-server on the Raspi first.
> 
> `adb start-server`
> `scrcpy --max-size 1440`

![IMG_20210317_171335.jpg](https://user-images.githubusercontent.com/64853498/111501138-ff8eb300-8744-11eb-9134-6d7795f2a014.jpg)

How did you get it? Thanks

**Comment by decodeais** [comment]
Sorry I don't remember that problem. I think I took  beta version. So the first try worked.

**Comment by WouterJD** [comment]
Streaming from smartphone to TV is beyond the scope of the FortiusAnt documentation; I draw a line somewhere :-)
Same holds for smartphone -> Raspberry -> TV

Thanks for sharing anyway

**Comment by MeanHat** [comment]
@BikeBeppe64 - I use a Raspberry Pi3 running FortiusANT connecting via Bluetooth to an Android smart phone running Zwift. This displays on a TV using a Chromecast attached the the HMDI input on the TV. Works perfectly. Hope this helps.
