### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by thedutchviker** [WouterJD/FortiusANT#280]
Hi wouter
Zou t graag ns proberen met fortiusant software, bv omvride te testen op mn ouwe i-magic. Rij nu nog tts 3.13....
Waar kan ik de nodige download kopen?

**Comment by thedutchviker** [comment]
By the way, grt uit zuid limburg....

**Comment by WouterJD** [comment]
Hoi @thedutchviker begin in de wiki
https://github.com/WouterJD/FortiusANT/wiki

Klik op de lini naar het manual
Daarin vind je installatie instructies.

Github software is gratis, bezoek de sponsor pagina voor de mogelijkheden: https://github.com/sponsors/WouterJD

**Comment by thedutchviker** [comment]
Hi Wouter

Super. Ik ga ns een poging wagen. 

Met vriendelijke groet

Eric Komen
