### ISSUE TITLE
ISO Dev to buld stand alone Raspberry based FortiusANT unit

### ISSUE THREAD

**Issue by Aduffy** [WouterJD/FortiusANT#285]
First off my apologies if this post is inappropriate here. 

I am not familiar with Python or Raspberry Pi, but i do own an IGenius Multiplayer T2000 (with black track) that I had almost give up on until i came across this project. 

Assuming the  IGenius Multiplayer T2000 is supported, I would be interested in hiring some one here (and/or sponsor this project!)  to set up a Raspberry pi based board with FortiusANT to bring some life back to my  IGenius Multiplayer T2000.

**Comment by WouterJD** [comment]
Contact me 1:1 on Messenger; I deliver pre-configured Raspberry's. I suppose that's what you look for.
https://link.marktplaats.nl/m1679975778
