### ISSUE TITLE
No Tacx trainer found

### ISSUE THREAD

**Issue by Scissors200** [WouterJD/FortiusANT#297]
I have a Tacx T1932. I have installed everything like in the manual. I use one laptop and two ANT+ dongles. When I start Fortius ANT I and click locate I keep getting the message No Tacx trainer found. 

I already removed all Tacx software,

Need some assistance, please!

**Comment by Scissors200** [comment]
Found the issue! The windows executable didn't quite do the job completely. So I recommend to read the full installation and not skip to 3.9.

Had to connect the ANT to the USB manually.

**Comment by WouterJD** [comment]
Great to see that you managed. Good luck!
