### ISSUE TITLE
FortiusANT.exe blocked by NortonSecurity

### ISSUE THREAD

**Issue by jjmasc** [WouterJD/FortiusANT#298]
Hi 
Norton detects Heur.advml.b when  i download FortiusAnt.exe on windows10
Is this a false positive?

**Comment by WouterJD** [comment]
I assume it is; the .exe unzippes itself and then executes the python software.
This probably contains constructions that make antivirus programs nervous.

If downloaded from github it should be OK

**Comment by jjmasc** [comment]
Thanks 
I' ve downloaded  source code package and install .
No warning.
I will begin to use it tomorrow or the day after, depends on Amazon
I posted on issue #14
