### ISSUE TITLE
Two T1932 headunits, different reaction

### ISSUE THREAD

**Issue by GewoonGijs** [WouterJD/FortiusANT#299]
Hi All,

I am already using FortiusANT with a T1901 magnetic brake, but now I clould lay my hands on a very cheap Motorbrake T1941. The odd thing is that I now have two T1932 head units, that seem to react differently.

- unit 1:  (with PD1204) on the back seems to work flawless
- unit 2: (with PD 0704) is reacting quite often with 'Tacx head unit returns insufficient data, len=24'

I also notice that the frequency of the green LED on the T1932 is flashing with a much lower frequency on unit 2. Can anyone explain this phenomena?

I suspect there has been an update of the hard/firmware which made the T1932/PD1240 faster. Can that be the case? 

If I don't activate pedal stroke analysis the insufficient data message is appearing less ofte, but I do notice it every time I click the Start or Stop  buttons. 

Furthermore the PD1204 seems to react better on pushing the buttons on the T1932 head unit.

**Comment by WouterJD** [comment]
All I can say is check the connections, including the 220V on the power back. May cause interference.
I have no knowledge on the firmware versions, so cannot help there

**Comment by WouterJD** [comment]
Since there is no communication here, I assume can be closed.
If not happy to reopen
