### ISSUE TITLE
Assertion error in usbTrainer

### ISSUE THREAD

**Issue by HeathB7** [WouterJD/FortiusANT#306]
Can anyone please assist with this new issue dropping connection between trainer and app

![image](https://user-images.githubusercontent.com/83499642/117432085-10f27f80-af7e-11eb-93a4-508084152edc.jpeg)

**Comment by WouterJD** [comment]
@HeathB7 with the current code, this is line 2480
So you're some updates behind

Perhaps good to download the most recent code; even though this check was not reported before
