### ISSUE TITLE
Ceinture Cardio "Coospo"

### ISSUE THREAD

**Issue by regis65** [WouterJD/FortiusANT#307]
Bonjour,
Depuis que j ai mis la nouvelle version de  
Fortisant + (6.1),la ceinture cardio Coospo  n apparer pas sur la page j ai juste les vitesses avant et l arrière mais pas mes pulsations cardiaque.
Comment réparer cela.
Sportivement 
Regis

**Comment by BikeBeppe64** [comment]
Maybe this help, Raspberry PI 4 

![Screenshot_2021-05-09-16-03-14-551_eu.virtualtraining.jpg](https://user-images.githubusercontent.com/64853498/117577168-f2f55e00-b0e8-11eb-92a0-416c9f68b9ad.jpg)

 Bluetooth

**Comment by regis65** [comment]
J ai oublié de dire que mon Fortisant + tourne sous windows 10.

**Comment by WouterJD** [comment]
Regis, could you provide some more information?

**Comment by regis65** [comment]
C est une ceinture Cardio coospo et je n arrive pas a le faire apparaître sur la page de lancement,même la page me dit de mauvais Watts

**Comment by WouterJD** [comment]
Regis c'est le vrai minimum d'informations pour comprendre ce que tu veuz faire.
S'il vous plait explique mieux pur comprendre.

"la ceinture cardio Coospo n apparer pas sur la page": quel page de quel application sur quel systeme?
:-)

**Comment by WouterJD** [comment]
Since there is no communication here, I assume can be closed.
If not happy to reopen
