### ISSUE TITLE
T1932 and T1901 Erg Mode Questions

### ISSUE THREAD

**Issue by StFalagar** [WouterJD/FortiusANT#317]
Hi Everyone...

I have been using the Fortius trainer and Head Unit (t1932) with great success and I am now embarking on getting the Fortius Brake working with a Raspberry Pi as Headunit as per @totalreverse's page.  In doing that... I have switched out my Fortius Motorbrake with an old Flow Magnetic Brake...    Everything seems to be working fine although it seems that Erg Mode is very limited with this brake.... I experience the following:

- I cycle at a target of 100w and then the actual power overreads at about 150w....  (On the Fortius brake it would auto adjust down to 100w)
- I then change gears on my bike to an easier gear until the actual and target is more or less the same...  
- I then start increasing the target power on the T1932 head unit and the brake follows which is fine and to be expected however, when I get to about 200w target power, the trainer stops applying the brake... i.e. if I go above 200w it just stays at 200w.  (On the Fortius Brake it would just keep adjusting to whatever wattage I specify)
- The same happens if I do intervals on Zwift and I ride at 210 and the interval target jumps to 115... the trainer will only adjust down to about 158w.

Is this the way the T1901 is supposed to work? Do you have to use erg mode with a combination of gears in order to cater for jumps in power or is this something I can configure or maybe update the firmware of the headunit?

Also I have gone through most other threads on here regarding this combination of Headunit and Brake but couldn't find similar comments so apologies if I missed anything...

Thanks a lot...

**Comment by WouterJD** [comment]
I do not understand your configuration. What head-unit and what brake do you use?

The magnetic brake is VERY different from the motor brake.
It's not only you but also Tacx finding this difficult; implementation on the "old" headunit is very different from the T1932.
The interface for both headunits is different, the logical behind it unclear to me since Tacx does not describe it.
You could look in usbTrainer.py BUT that documents the USB-interface, not how the brake-interface works.

**Comment by StFalagar** [comment]
Hi Wouter...

Thanks for your reply... I normally use the normal Tacx Fortius... i.e. motor brake and blue and white head unit.
Now I have switched the motor brake out for a T1901 magnetic brake and getting this scenario.  Still using the T1932 Blue and White Head Unit. 

Thanks

**Comment by WouterJD** [comment]
Well...from what I understand the motorbrake is more advance than the magnetic brake.
The manual does give some additional info on that, refer to chapter 5.

PS1. Check that FortiusAnt correctly detects Magnetic brake (message on console)
PS2. what is the reason to switch brake?

**Comment by StFalagar** [comment]
Ok... I have read there but will have a look again...

The Magnetic Brake came over my path at a very low price... and I read the below thread on Totalreverse's Github page so I want to try and get the Motor Brake working with my Raspberry Pi 3 and then run the Magnetic Brake using the T1932...  This way I can get my wife to join me in Zwift :)  I also have a friend who is using the same config (Blue and White T1932 Headunit with Flow T1901 Brake) so I would like to try and optimize it and get it working properly.

I like the feel of the Magnetic Brake... very smooth although a bit disappointed that in ERG it's behaving like this...

https://github.com/totalreverse/ttyT1941/issues/21#issuecomment-764018525

**Comment by WouterJD** [comment]
What I understand, you have two configurations:
<unknown> - USB -> T1932 headunit -> T1941 motor brake
Raspberry Pi3 - USB -> T1932 headunit -> T1901 magnetic brake

To study in detail, grab usbTrainer.py.

In short:
- The T1932 headunit behaves completely different when a T1941 or a T1901 is connected.
- T1941: the requested power is translated into a resistance (using the wheelspeed) and the brake delivers that resistance
- T1901: the requested power is translated through a table to one out of 13 resistance-options  and the brake delivers that resistance
Refer to chapter 5 how to optimize riding on the T1901.

In my opinion, the older magnetic brake was fit for the purpose at the time of creation: do some simulation riding; actually the first step after the manually adjusted magnetic brakes.
Virtual reality and structured training demand more advanced trainers, the Fortius T1941 looks like a big step forward.
Next step are the direct drive trainers from today.

I am not a technology follower, so may be aside.

Conclusion: the magnetic brake can do ERGmode (structured) training and GradeMode (simulations); the motor brake is more advanced.

Read chapter 5 and 6; it shows that there are happy users of the magnetic brake; perhaps when comparing the magnetic brake loses.

Mind to keep a high wheelspeed and use the virtual gear. In GradeMode use the -G option as documented.

IT CAN WORK.

**Comment by StFalagar** [comment]
Thanks very much Wouter....

I really enjoyed doing free ride with the Magnetic Brake.... It is more smooth on big climbs etc.
I'll play around with those options on FortiusAnt as per chapter 5 and 6.

Thanks again for your prompt responses as always...

**Comment by WouterJD** [comment]
:-)

**Comment by StFalagar** [comment]
@WouterJD after training with the t1901 for a few days and looking at the documentation again, it seems that this is just a limitation on the Brake.  Unlike with the Fortius where you can just pedal away, the T1901 either gets to 1900 on the low side or 3750 on the high side at which point you have to shift gears on the bike.  The Erg mode then works fine from there again...

Aside from that... to me it feels more like actual riding than the motor brake but that's really nitpicking.  Pity the same limitation in Grade Mode means you can do about 5 degrees climbs at most but hey... to be able to use this in Zwift is awesome.

Thanks again

**Comment by WouterJD** [comment]
@StFalagar thanks for feedback.
All I used is the Fortius, and know the other systems from software point of view only.

Refer to the manual, section 2.5 which is a copy from Tacx docu (I hope they forgive me).
It shows the working-areas of the trainers
