### ISSUE TITLE
What to buy?

### ISSUE THREAD

**Issue by frankhommers** [WouterJD/FortiusANT#320]
This might not be the right place to ask this. But I am unaware of another forum on this topic.

I want to start Zwifting using FortiusANT, but what would be the best trainers and addons to buy (second hand) to have the most fun experience?

I currently have a Tacx which too old too be compatible.

**Comment by WouterJD** [comment]
Agree with @rcerrie 

Tacx Fortius takes some space, but is stable
The new models are more flexible and occupy less space, e.g. the Genius.

Check the manual, where I copied specs as provided by Tacx; section 2.3
