### ISSUE TITLE
TFT Display not working correctly

### ISSUE THREAD

**Issue by frankhommers** [WouterJD/FortiusANT#323]
![image](https://user-images.githubusercontent.com/7355878/134787432-2c1b692e-84fe-499b-bc8f-e937968ac9f9.png)

I have this problem. It might that I have a slightly different LCD screen.

I started it with -O display/90 

It's this item: https://nl.aliexpress.com/item/1005002669311522.html

**Comment by MeanHat** [comment]
Hi @frankhommers - your display is 135 x 240; the code is written for a 240 x 240 display. Line 9 of https://github.com/WouterJD/FortiusANT/blob/master/pythoncode/raspberry.py describes this. You could modify the code but it may be easier to buy a 240 x 240 display

**Comment by WouterJD** [comment]
I agree with @MeanHat !

**Comment by frankhommers** [comment]
Ah OK. I'll do that.
