### ISSUE TITLE
New to his, need help :) 

### ISSUE THREAD

**Issue by tommmmvh** [WouterJD/FortiusANT#325]
Hi!

I downloaded Fortius ANT. And I installed everything via the quick install guide (windows) in the user manual. I use the and Tacx flow multiplayer with the T1901 motor. And I have a garmin ANT+ dongle. 

When I open FortiusAnt I see my speed and watts. And I see that the trainer is connected but this is the wrong type. How can I change this. Also when I check the ANT+ dongle it's a different type than the garmin, right ? 
[](url)

![afbeelding1](https://user-images.githubusercontent.com/92363252/137160457-6d54fd44-4caa-4f59-83ac-ef97adbcdd47.png)

My plan is to use Zwift on the same computer as FortiusAnt if this is possible. Do I need another ANT+ dongle ? I tried to run the FortiusAnt script on my PC and downloaded Zwift on my phone (Galaxy S21) and tried to connect but it didn't find the dongle. What am I doing wrong.

**Comment by WouterJD** [comment]
Ref [TotalReverse](https://github.com/totalreverse/ttyT1941/wiki#a-closer-look-at-the-t1902-and-t1942-head-units)
Note, though, that T1902 and T1932 are headunits.
The T1932 headunit can handle the Magnetic AND the Motorbrake. 

Look at the console (black window) what is displayed there; pleae copy.
