### ISSUE TITLE
Vortex T1961+ T1962 head unit, dongle tacx

### ISSUE THREAD

**Issue by Rybsonzst** [WouterJD/FortiusANT#327]
Hi!
Firstable great job of Wouter, you're amazing.

Now my issue.
Vortex T1961+ display T1962.
I did everything from manual, but unfortunately i can't connect my trainer to app.
Im using tacx dongle T2028, app finding dongle, but then i get a info from attachment.
What i can do more to fix it?
![received_667046570932481](https://user-images.githubusercontent.com/93425614/139526331-974a5201-133f-4245-9977-91395d4208e3.jpeg)

**Comment by WouterJD** [comment]
Welcome to the FortiusANT community
- - -
I'm always curious to know who I communicate with, where FortiusANT is used and what configuration is used.
Please tell me what bundle did you buy, and what brake and what head unit do you use?
I would therefore appreciate that you introduce yourself; perhaps leave a comment under issue #14.
You could also consider to visit [the sponsor page](https://github.com/sponsors/WouterJD)
- - -

Please provide command line you use

**Comment by Rybsonzst** [comment]
Im trying to start it on windows with executable file.
I hope this is what You mean.

**Comment by WouterJD** [comment]
You can use the executable, but specify -t Vortex, otherwise FortiusAnt does not know what type of trainer to look for.
please refer to manual section 4.2 page 39

**Comment by WouterJD** [comment]
Hi @Rybsonzst how do you proceed?

Since there is no communication here, I assume can be closed.
If not happy to reopen
