### ISSUE TITLE
Set permanent PowerMode on Raspberry Pi Zero W.

### ISSUE THREAD

**Issue by planetSammy** [WouterJD/FortiusANT#338]
I have a problem switching from GradeMode to PowerMode after calibrating my Genius Trainer. If I start RGT Cycling on my iPhone, my Raspberry Pi immediately switches to PowerMode, but not when I start RGT Cycling on my Win10 Computer . Is it possible to use the PowerMode permanently after calibration?

I use the following settings: ~/FortiusANT/raspberry/FortiusAntMain.sh -a -b -H-1 -P -t Genius

After calibration my workaround is to start RGT Cycling first with my iPhone and then establish a connection to my win10 pc...

Best regards Sammy

**Comment by planetSammy** [comment]
Now I tested a connection to an android device, works fine, only win10 does not switch to powerMode 🤔

**Comment by WouterJD** [comment]
The CTP (RGT on your case) can send two types of command:
- power mode, e.g. asking for 123Watt
- grade mode, e.g. asking for 15%

No settings are required, if FortiusAnt does not switch to power mode, no such command is received. 


The -P flag is only useful when pairing with (for example) Zwift and TrainerRoad, to instruct FortiusAnt to listen to the power mode commands from TrainerRoad and ignoring the grade mode commands from Zwift. 

That is not applicable in your situation

**Comment by WouterJD** [comment]
If RGT on windows continues not to work, please attach logfile as created with - d127

**Comment by WouterJD** [comment]
Since there is no communication here, I assume can be closed.
If not happy to reopen
