### ISSUE TITLE
Tacx Genius T2021 not found

### ISSUE THREAD

**Issue by BastiaanTol** [WouterJD/FortiusANT#339]
Hello WouterJD,

I,m Bastiaan from Twello in the Netherlands. I bought the Tacx Genius T2021 from your Daughter? this week. Nice to see that you have put in so much effort in reviving old trainers. I cant connect the trainer with the Fotius Ant.. Yet. But i will post an issue when i have puzzeled out the manual. 

Hope it works out!

**Comment by WouterJD** [comment]
Hi bastiaan. You can connect. - t Genius; see manual👍

**Comment by BastiaanTol** [comment]
Hi Wouter,

Thank for your reaction. I have installed the Fortius Antifier and studied the manual.. I have connection with the ANT+ but the trainer stil is not found. I'm working with one laptop (windows 10).
I was told that the Fortius Ant schould work with one ANT+ dongle. But when i look at the picture in the manual under par 3.2.4 it seems that i need two dongles is that correct? Or is there an other way?

![InkedANT_LI](https://user-images.githubusercontent.com/95050522/143719730-c50a89a3-7dfd-4458-9c4a-e14ff7e72040.jpg)

Looking forwar to your reaction.

Groeten,
Bastiaan

**Comment by WouterJD** [comment]
FortiusAnt uses one ANTdongle to communicate to a) a CTP, like Zwift, and b) an Ant-based trainer.
If running on same PC a second dongle is required for Zwift itself. 

> I was told that the Fortius Ant should work with one ANT+ dongle.

The statement may be correct but is incomplete; Zwift needs the other one.

OR you chose to use BLE

**Comment by BastiaanTol** [comment]
Ok Thanks!

**Comment by BastiaanTol** [comment]
Hi Wouter,
I have bought a second ANT+ and got it all running! 
Thanks again!

**Comment by WouterJD** [comment]
Succes, see you on strava!, I assume can be closed.
If not happy to reopen
