### ISSUE TITLE
Calibration Issues Tacx T2021 Genius

### ISSUE THREAD

**Issue by liga140623** [WouterJD/FortiusANT#346]
Hi All,

I managed to install FortiusANT on my Mac and it started to recognize my Tacx Genius - I am however stuck with the next step, namely the calibration. FortiusANT tells me to nudge the wheel forward, so I started to turn the pedals but then nothing happens. Any suggestions on how I can get my Tacx calibrated? What am I doing wrong?

Many many thanks in advance and happy holidays!!
L.

**Comment by WouterJD** [comment]
Welcome to the FortiusANT community
- - -
I'm always curious to know who I communicate with, where FortiusANT is used and what configuration is used.
Please tell me what bundle did you buy, and what brake and what head unit do you use?
I would therefore appreciate that you introduce yourself; perhaps leave a comment under issue #14.
You could also consider to visit [the sponsor page](https://github.com/sponsors/WouterJD)
- - -
Even when you apparently resolved the issue!
