### ISSUE TITLE
M5StickC PLUS ? 

### ISSUE THREAD

**Issue by Aduffy** [WouterJD/FortiusANT#349]
Can FortiusANT be installed on these? 
https://shop.m5stack.com/products/m5stickc-plus-esp32-pico-mini-iot-development-kit?variant=35275856609444

**Comment by WouterJD** [comment]
I have no clue
You need USB, ANT and/or BLE support

**Comment by WouterJD** [comment]
Since there is no communication here, I assume can be closed.
If not happy to reopen
