### ISSUE TITLE
Genius brake not found

### ISSUE THREAD

**Issue by Anniehoho** [WouterJD/FortiusANT#367]
Na vanochtend een goede sessie te hebben gehad, lukt het vanmiddag niet om de rem te kalibreren. De fortius ANt maakt connectie met de smartfone en ook met de Genius, maar er is geen interactie tussen stijgingspercentage en weerstand op de rem. Wat te doen?

**Comment by WouterJD** [comment]
Welkom in de FortiusANT community
- - -
Ik ben altijd nieuwsgierig met wie ik communiceer, waar FortiusANT wordt gebruikt en in welke configuratie.
Welke bundle heb je gekocht, en welke rem en head-unit gebruik je?
Vertel meer over jezelf, eventueel onder issue #14.
- - -

Hoi @Anniehoho jammer dat eea niet meer werrkt. Je geeft echter niet veel info. 

Begin Eens met een foto van FortiusAnt, bij voorkeur met een tracefile (-d255)

**Comment by Anniehoho** [comment]
Ik gebruik de Raspberry PiO met Forrius Ant en de Break is de Tacx Genius Brake T2021. Plaatjes heb ik bijgevoegd.  Ook van het script in een video omdat ik niet zo handig ben dat ik een tracefile weet te pakken. 
![IMG_20220129_173909](https://user-images.githubusercontent.com/98264228/151669433-3637b5cb-307a-4198-aec1-2d2535ad4aab.jpg)
![IMG_20220129_173005](https://user-images.githubusercontent.com/98264228/151669435-bc22cab9-e684-4a53-8e30-b05a085c799b.jpg)
![IMG_20220129_173806](https://user-images.githubusercontent.com/98264228/151669437-df9a4525-1924-41ad-a6b2-c4162731e927.jpg)
![IMG_20220129_173009](https://user-images.githubusercontent.com/98264228/151669439-4e6bda91-ee1f-4013-9e50-979fd403f27b.jpg)
![IMG_20220129_173724](https://user-images.githubusercontent.com/98264228/151669441-d4869096-15a9-44af-b33c-b1edd49a19e1.jpg)

**Comment by Anniehoho** [comment]
Ik hoop dat je mij kan helpen

**Comment by WouterJD** [comment]
Actually, the messages look good "Pair with Tacx Genius this can take a minute". What happens after that minute?

**Comment by WouterJD** [comment]
You say you are not so very handy, but did a series of good steps already:
- Raspberry Pi0
- Start FortiusAnt with -t Genius option; requiring ANT-dongle
- ANT-dongle is present in your pi
- ...

Just some additional steps and it will work; assuming no device is broken.

**Comment by WouterJD** [comment]
Since there is no communication here, I assume can be closed.
If not happy to reopen

**Comment by Anniehoho** [comment]
Unfortunately I am to busy to respond quickly. In two weeks I will get back on the issue (which is not solved) Verzonden vanuit Mail voor Windows Van: Wouter DubbeldamVerzonden: dinsdag 15 februari 2022 13:18Aan: WouterJD/FortiusANTCC: Anniehoho; State changeOnderwerp: Re: [WouterJD/FortiusANT] Genius brake not found (Issue #367) Since there is no communication here, I assume can be closed.If not happy to reopen—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you modified the open/close state.Message ID: ***@***.***>

**Comment by WouterJD** [comment]
As soon as you have time, we can reopen and pick it up.
