### ISSUE TITLE
GUI in Ubuntu

### ISSUE THREAD

**Issue by mtbiker22** [WouterJD/FortiusANT#37]
I am setting up a "new" compuer for FortiusANT/Zwift/GoldenCheetah/etc.

I can run the GUI but when I press start I get this error:

[xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python3: ../../src/xcb_io.c:165: dequeue_pending_request: Assertion `!xcb_xlib_unknown_req_in_deq' failed.
Aborted (core dumped)

Any ideas?

**Comment by WouterJD** [comment]
Please send logfile -d 127
