### ISSUE TITLE
Power mismatch betwwen FortiusAnt and Stages powermeter

### ISSUE THREAD

**Issue by GewoonGijs** [WouterJD/FortiusANT#370]
Hi all, I happen to have 2 bikes. One that I use outside, with a Stages gen2 power meter and one inside on the Tacx Fortius with FortiusAnt. I see a big difference in power between the two.

Outside I did a quite easy ride and had a average power of 222 W with a mean HR of 145 (distance 44 km, duration 1:39) and today I was inside doing a Zwift TdZ average of 227 W with a mean HR of 168 bpm (duration 0:48). The indoor training was definitely harder.

Which measurement should I trust more?

**Comment by WouterJD** [comment]
You calibrate the power, using the bike with power meter on the fortius. The use the FortiusANT parameters - P etc to adjust

**Comment by WouterJD** [comment]
Since there is no communication here, I assume can be closed.
If not happy to reopen
