### ISSUE TITLE
Raspberry : No Figure with Speed,Cadence & Power appears

### ISSUE THREAD

**Issue by BikeBeppe64** [WouterJD/FortiusANT#374]
hi Wouter, using Raspberry,  the figure with Speed, Cadence and Power, does not appear, even if everything work well.  No one else has the same situation?

![Screenshot_2022-02-08-16-43-33-40_99c04817c0de5652397fc8b56c3b3817.jpg](https://user-images.githubusercontent.com/64853498/153022457-6ab44935-f471-457f-8f04-6e4e9f447825.jpg)

**Comment by WouterJD** [comment]
Did not see this before.
Please provide as much info as possible, I will help next week

**Comment by BikeBeppe64** [comment]
Wouter, please close this mine because getting a fresh Raspberry Os "Buster", FortiusAnt now Is fine again....
