### ISSUE TITLE
Best way to installing on Raspberry 

### ISSUE THREAD

**Issue by mamu0015** [WouterJD/FortiusANT#375]
Nice project.

is there a best way installation guide where i can find the different ways of use?
with LED, with display, headless....
actual i am a bit confused about how to install.

or has anybody created an iso file of a ground installation (is this possible?)?

**Comment by mamu0015** [comment]
thank you,
I only saw the installation of Windows an Linux,

the big part special for Raspberry is exactly what i was looking for :-)

**Comment by WouterJD** [comment]
Happy you found it; I assume can be closed.
If not happy to reopen
