### ISSUE TITLE
Raspberry display - update to dejavu fonts

### ISSUE THREAD

**Issue by MeanHat** [WouterJD/FortiusANT#379]
Hi @WouterJD - I had to reinstall FortiusANT on an RPi0W with ST7789 display. When running the various scripts I received a warning for  [https://github.com/WouterJD/FortiusANT/blob/master/raspberry/OutputDisplay_Dependencies.sh](url) in line 17 : `sudo apt-get install ttf-dejavu`
It appears that the fonts have been updated and can be replaced with `sudo apt-get install fonts-dejavu`
Would  you like to consider this for the next update?
Best rgds - Keith

**Comment by WouterJD** [comment]
fonts-dejavu added, ttf-dejavu left present.
I assume installing both will not hurt; can remove if needed. Somebody reading the script will understand
