### ISSUE TITLE
Online trainer?

### ISSUE THREAD

**Issue by goupet** [WouterJD/FortiusANT#382]
Hallo

Bestaan er gratis online trainers die weinig geld kosten. en toch degelijk zijn. Of zijn ze allemaal betalend? Ik heb er ondertussen een 5 tal gezien... en ik weet neit welke de beste is.

Dank je wel voor dit super programma. De link is gelukt tussen Vortextrainer en de pc. Juist de afstelling van de snelheidsregelaar moet ik nog zoeken. Nu nog het zelfde doen voor de bushidotrainer....

**Comment by WouterJD** [comment]
Peter, ik zou het niet weten.
Gezien de ANT en/of BLE link die nodig is lijkt me niet, maar wie weet...

"Beste" is een rekbaar begrip, wil je gestructureerd trainen, enhanced virtuality of groeps-evenementen...
Probeer ze uit en je ontdekt wat je past, ze hebben allemaal wel een trial periode.

Misschien dat iemand nog reageert, moet wel nederlands spreken :-)

**Comment by WouterJD** [comment]
Since there is no communication here, I assume can be closed.
If not happy to reopen
