### ISSUE TITLE
Trainer is a bit dancer (Raspberry Pi4 buster)

### ISSUE THREAD

**Issue by BikeBeppe64** [WouterJD/FortiusANT#385]
Hi any of you have a situation like mine using Bluetooth?

https://user-images.githubusercontent.com/64853498/156856100-3df8032a-0238-4c61-af0a-901f6e1c51ca.mp4

**Comment by decodeais** [comment]
I had this effect on my RP too. The sensors wete flashing, connection was passibke, but controle of trainet wad not possible. My new installation script was the solution. 
[https://github.com/decodeais/FortiusANT/blob/master/raspberry/PiBulleye_Install.sh](https://github.com/decodeais/FortiusANT/blob/master/raspberry/PiBulleye_Install.sh) .

**Comment by decodeais** [comment]
It is the same problen like issue  #372.  The install script fixes the node installation.

**Comment by BikeBeppe64** [comment]
> I had this effect on my RP too. The sensors were flashing, connection was possible, but control of trainet was not possible. My new installation script solved the problem.
> [https://github.com/decodeais/FortiusANT/blob/master/raspberry/PiBulleye_Install.sh](https://github.com/decodeais/FortiusANT/blob/master/raspberry/PiBulleye_Install.sh) .  

I'll try your solution. Thanks in advance

**Comment by decodeais** [comment]
> > I had this effect on my RP too. The sensors were flashing, connection was possible, but control of trainet was not possible. My new installation script solved the problem.
> > https://github.com/decodeais/FortiusANT/blob/master/raspberry/PiBulleye_Install.sh .
> 
> I'll try your solution. Thanks in advance

Please  tell me wether it worked for you or what problem appeared.

**Comment by WouterJD** [comment]
@BikeBeppe64 nice script; all-in-one :-)
What is the major change, so that it can be added to the current scripts.

I did not create a big script to keep the scripts simple; but it requires to start them one-after-the-other.
In short future we will have the option to use NodeJs and/or bless, which would require parameterization...

**Comment by decodeais** [comment]
In this case it was the problem from #372 package-lock.json.
The second is to erase the old installation complete at the beginning (a relict of the crazy package-lock effects). For OS Bullseye there is needed  another wxpython version. I found it at the Ubuntu distribution ( already compiled). I tried to reduce the the amount of questions I'm am asked by the script with default yes, for example.
But this script is a product of try and error, until it worked from a fresh OS install.
But your new bleak/bless version makes the node part obsolete, I think.

**Comment by BikeBeppe64** [comment]
> > > I had this effect on my RP too. The sensors were flashing, connection was possible, but control of trainet was not possible. My new installation script solved the problem.
> > > https://github.com/decodeais/FortiusANT/blob/master/raspberry/PiBulleye_Install.sh .
> > 
> > I'll try your solution. Thanks in advance
> 
> Please  tell me wether it worked for you or what problem appeared.

@decodeais installed your script and at the moment works fine

< VID20220325104001.mp4 -->

**Comment by BikeBeppe64** [comment]
> > > I had this effect on my RP too. The sensors were flashing, connection was possible, but control of trainet was not possible. My new installation script solved the problem.
> > > https://github.com/decodeais/FortiusANT/blob/master/raspberry/PiBulleye_Install.sh .
> > 
> > I'll try your solution. Thanks in advance
> 
> Please  tell me wether it worked for you or what problem appeared

@decodeais installed your script and everything works fine (RGT = CPT)

![IMG20220325103641.jpg](https://user-images.githubusercontent.com/64853498/160096802-33191503-b44b-4d86-bf05-981526040e13.jpg)

**Comment by WouterJD** [comment]
Please recheck with bless version, then the node.js issues should be gone.

**Comment by WouterJD** [comment]
Hi @BikeBeppe64 ble/bless is now released and the master branch.
Is this issue still happening?
