### ISSUE TITLE
The development branch https://github.com/WouterJD/FortiusANT/tree/Implement-BLE-using-bless 

### ISSUE THREAD

**Issue by jujroy** [WouterJD/FortiusANT#387]
Hello, not sure if this problem is unique to me.
Using 2 Windows 10 laptops
T1932
Motor Brake (120V)

I recently tested subject new development branch available on GitHub.

The resistance provided by the motorbrake is unrealistic/too weak. Power displays in excess of 1000W and speed in excess of 60km/h. JSON attached.  I am a fair cyclist but I never generated 1000W plus to this day :)  Cheers
[FortiusAntSettingsjson.docx](https://github.com/WouterJD/FortiusANT/files/8497976/FortiusAntSettingsjson.docx)

**Comment by WouterJD** [comment]
Hi @jujroy 

When implementing BLE I do not think I touched the piece of code that calculates powers.
But you never know...

I published BLE/bless today and please retest.
If the problem persists, please re-open the issue.
