### ISSUE TITLE
connection to zwift phone unstable, connection to zwift pc reasonable

### ISSUE THREAD

**Issue by Lucus123** [WouterJD/FortiusANT#388]
hello,

the following happens:
pairing zwift via BT to the fortiusant trainer installed on a rpi 3b+ works fine.
connection is frequently lost to fortiusant in the pre-ride pairing screen (it does register wattage if i cycle, but no cadence) if i strt a ride it immediately says "Connection faillure" in the upper left corner of the screen and whatever i do, no data is registered.

if i pair the fortiusant to a windows pc running zwift via BT, everything works as expected, BUT i get frequent disconnects in the zwift app, no data is registered form the trainer (speed drops to 0, wattage to 0 etc) the fortiusant pi does not seem to lose connection though. if i keep cycling the connection will return, but it will work until the next disconnection happens.

i am running a raspi 3b+ with debian buster.
i tried to get the ble-bless branch installed but i have no idea how i should do that on the pi.

**Comment by WouterJD** [comment]
Hi @Lucus123 BLE/bless is released. Please give it a try.
If problems persist, please do not hesitate to reopen the issue.
