### ISSUE TITLE
FortiusANT Installed and Working With ANT.  Instructions for BLE?

### ISSUE THREAD

**Issue by Dmlrmed1** [WouterJD/FortiusANT#389]
I apologize if this is already answered but I can't seem to find specific instructions for BLE.  When I plug my BLE into the USB drive (like I would with my ANT) and launch FortiusANT the BLE device is not recognized.  Seems to work ok for my ANT.  Is there something else I need to install?  I plan to use Zwift on iPad and need BLE.

Thanks

**Comment by WouterJD** [comment]
Welcome to the FortiusANT community
- - -
I'm always curious to know who I communicate with, where FortiusANT is used and what configuration is used.
Please tell me what bundle did you buy, and what brake and what head unit do you use?
I would therefore appreciate that you introduce yourself; perhaps leave a comment under issue #14.
You could also consider to visit [the sponsor page](https://github.com/sponsors/WouterJD)
- - -

With the currently published FortiusAnt software (master branch), node.js must be installed as is described in the manual.
The version that is to be published (Implement-ble-using-bless branch) is more likely to discover your BLE-dongle, note the version of the BLE-dongle to be used (also described in the manual).

**Comment by Dmlrmed1** [comment]
Thanks for the quick reply.  I see the instructions on how to install node.js and zadig,  Thanks.  I plan to bring my Tacx I-Magic back to life as a second trainer.  Still great riding outside in Northeast Ohio right now but will be riding indoors in a few months.  I am using a Windows 10 computer.

**Comment by WouterJD** [comment]
Hi @Dmlrmed1 yesterday I promoted the latest software to thge master branch. Installing that version allows to use BLE without instyalling nodejs. Just requires a modern BLE dongle under windows.

**Comment by Dmlrmed1** [comment]
I am trying to use an Insignia Bluetooth 4.0 USB dongle.  Is this compatible?  It looks like I need to get a 5.0?

**Comment by WouterJD** [comment]
Yes, note that on Windows a BLE-5 dongle must be present BUT the native windows driver is OK (no zadig required)
When BLE-4 is available, Node.js must be used

**Comment by WouterJD** [comment]
Hi @Dmlrmed1 anything I can assist with, or can issue be closed?

**Comment by Dmlrmed1** [comment]
Thanks.  Out of town but will try with BLE-5 when I get back.

**Comment by WouterJD** [comment]
See you soon

**Comment by Dmlrmed1** [comment]
So I'm back at it again trying to get bluetooth to work.  I decided to use my Insignia Bluetooth 4.0 USB and installed Node JS.  When I launch FortiusANT.exe the trainer is detected but not the Bluetooth.  I tried to check the box in settings about using Bluetooth with Node JS but the restart just hangs.  What do I need to do and in what order.  For example, just because I installed Node JS do I need to start it somehow.  Not a techy.  Thanks.

**Comment by WouterJD** [comment]
Hi @Dmlrmed1 

I just tried to modify settings to activate the BLE interface using node.js and that works (on my system).
Why your system hangs I cannot tell right away.

It produces a json file containing, amongst the other settings.
```
{
    "bluetooth": {
        "nodejs": true
    },
}
```
-----
I usually use the scripts (the .bat files in startup) to start FortiusAnt, because that's the easy way to start with different sets of parameters. You could try that as follows:

You would use **FortiusAnt (exe).bat** (instead of double-clicking the executable itself from explorer).
That would start FortiusAnt with the default set of parameters.

You can modify that file, using notepad.
The file contains
`..\WindowsExecutable\FortiusAnt.exe`
which can be changed into
`..\WindowsExecutable\FortiusAnt.exe -a -g -b`
which means that it starts automatically, uses the GUI and communicates through bluetooth.

As soon as you are succesful with this, you can modify the parameters at will.

**Comment by WouterJD** [comment]
Wel @Dmlrmed1 at first follow the manual and then pose a question which is a bit more specific 😀

**Comment by WouterJD** [comment]
Hi @Dmlrmed1 replacing is not described specifically, good idea to add that to the manual. I will provide instructions later

**Comment by Dmlrmed1** [comment]
Hi again.  I decided to purchase a Bluetooth 5.0 dongle.  When I launch Fortiusant with the dongle inserted I do see both the tacx light and the Bluetooth light on the GUI.  However, when I launch Zwift on my iPhone and search for the trainer I do not see it showing up.  Is there something else I need to do?

**Comment by WouterJD** [comment]
How to upgrade? Manual page 22 describes how to download and install the FortiusAnt code. An upgrade can be done in a similar fashion, overwriting the existing code.
Of course, also git can be used. I suppose following the previous instructions will be easier.

When you start FortiusAnt, you have to press [Locate HW] to find the BlueTooth dongle and then [Start] to actually start the "bridge" between your Tacx and BLE. When that is operational, FortiusAnt should be found on your iPhone. See page 28 section 3.8.5.

Sorry that the sequence in the manual is not 100% logical. Perhaps it's caused by the multitude of trainers and interfaces that are supported.

If you have more questions, please let me know.

**Comment by WouterJD** [comment]
Git instructions

Installation using git can be done with `git clone https://github.com/WouterJD/FortiusANT.git`
To upgrade an installed version, the command `git pull origin master` can be used.

For more information, check https://git-scm.com/book/nl/v2

**Comment by Dmlrmed1** [comment]
Hello again.  I’ve followed your instructions.  Ran Fortiusant.exe, locate HW, Start.  GUI says Bluetooth interface open.  Both the Tacx and BLE ctp lights are blinking.  However when I run Zwift on iPhone the trainer does not show up.

**Comment by WouterJD** [comment]
Hi @Dmlrmed1 it's a stubborn environment you have.

_PS. do you use -b (nodejs) or -bb (bless)? As you will see, I use the latter, if you get no error-messages there should be no differrences._

Let's see.

You should have console + UI interface as below, always mind messages in the console (black window).
![image](https://user-images.githubusercontent.com/47486941/196144681-da5d145a-6067-4acf-9ab0-ad4b25e3ae46.png)

Now you can use Zwift to detect a trainer, but for BLE-debugging also the LightBlue app can be used on Android or iPhone.

The app comes up with the following window:
![image](https://user-images.githubusercontent.com/47486941/196145385-13478370-b2f2-4276-b3f8-e27283c7eedf.png)

And when opening the LT-ENTERTAIN (name of Windows PC where FortiusAnt is running):
![image](https://user-images.githubusercontent.com/47486941/196145590-d3783970-23cd-4d38-9fa3-b6559462b68e.png)
which shows the **Fitness Machine Feature** of FortiusAnt, indicating it's a trainer your could connect to.

This is the same process Zwift would do, then presenting the trainer as available to use.
Please let me know what your systems tell you.

**Comment by Dmlrmed1** [comment]
Again, thanks for trying to help.  Still having issues.  After installing driver for TP-Link Bluetooth and starting up with -bb I get the following:
![Capture1](https://user-images.githubusercontent.com/69309725/197349702-48298c9b-622a-4a20-b0d1-87cd6a152dc0.PNG)
Then when I START I see the following:

![Capture2](https://user-images.githubusercontent.com/69309725/197349798-2273ad49-6f32-438f-86e2-c39a27cebaa2.PNG)

Very frustrating.  Understand if you can't help.  Appreciate all that you've done up to this point.

**Comment by WouterJD** [comment]
Software seems ok

BUT what type is your BLE-dongle, it must be ble-5!

**Comment by Dmlrmed1** [comment]
Yes it’s 5

**Comment by WouterJD** [comment]
Hmmmm. The error returned by the bless library - until now - was caused by a BLE4 dongle. I remember that there are ble5 dongles around that are not.

I can post a question for the bless developer.

You could try another make of ble5 dongle
OR try - b and see to get node.js working, which does not require the ble5 features

**Comment by WouterJD** [comment]
Please provide all details of your ble5 dongle.

**Comment by Dmlrmed1** [comment]
I rolled back the driver, plugged in both an ANT and Bluetooth USB dongles and ran software.  Here's what I get:

![Capture3](https://user-images.githubusercontent.com/69309725/197404261-ec92d842-653b-44ea-84db-0b40ebb6fac7.PNG)

It appears to be working but I don't see the computer in either Zwift or Light Blue.  I feel I am very close.

**Comment by WouterJD** [comment]
Back to this: https://github.com/WouterJD/FortiusANT/issues/389#issuecomment-1280593341

**Comment by Dmlrmed1** [comment]
I’m happy to report that I can connect to Zwift by updating the Bluetooth driver.  Now my next issue is that my watts are way too high?  I am showing 500+ watts when it should be closer to 150 watts,  I did a run off but that didn’t fix it.  Even Zwift is giving me a message that my equipment isn’t calibrated correctly.

**Comment by WouterJD** [comment]
Hey, this is good and again a step further.
What did you change since:

> It appears to be working but I don't see the computer in either Zwift or Light Blue. I feel I am very close.

I'll get back to you shortly

**Comment by Dmlrmed1** [comment]
By updating the driver I was able to see and connect to Zwift

**Comment by WouterJD** [comment]
> Now my next issue is that my watts are way too high? I am showing 500+ watts when it should be closer to 150 watts

As I understand from the picture from last week, you have a T1932 headunit, hence a USB-connected Tacx trainer.

The trainer returns the actual resistance and using formula's (resistance and wheelspeed) the power is calculated.
The approach can be found in the manual and the exact formula's in the code: (https://github.com/WouterJD/FortiusANT/blob/master/pythoncode/usbTrainer.py, functions CurrentResistance2Power)

It may be that the calculated power does not match with a real power (measured witha power meter) and then the -p parameter can be used to adjust. A range of 10% is expected; defining -p90 or -p110 to adjust for that.

The difference you report is quite high; please provide more info to be able to thinbk about the cause.
Please study the manual, see sections 2.5 and 6.

**Comment by WouterJD** [comment]
Since there is no communication here, I assume can be closed.
If not happy to reopen

**Comment by jr111** [comment]
> By updating the driver I was able to see and connect to Zwift

Hello, I have same chipset, wondering what driver worked for you. I have tried various drivers, at one point LightBlue saw devices and changing values for steering, with another Zwift would occasionaly show a power meter with No Connection. Mostly want this for steering, works great for years with Ant. Wouter I commend you, my rusty Fortius still gets many km not possible without your work.
