### ISSUE TITLE
tacx app

### ISSUE THREAD

**Issue by andritre** [WouterJD/FortiusANT#39]
Hi, I wanted to know if you could use FortiusAnt for Tacx app descktop windows. I have tried but it seems that it cannot connect. Thanks AR

**Comment by WouterJD** [comment]
Tacx seems to do utmost best to close software. The desktop app does some checks that Zwift, TrainerRoad and others not do. Perhaps even hidden functions in the ANTinterface.

Who has a bright idea, please assist to get it Work🤔

**Comment by WouterJD** [comment]
In addition to previous; @RamonFigueras has tested with rouvy. That may be a good replacement for Tacx desktop app.

**Comment by RamonFigueras** [comment]
Is shown by the bycicle icon. See picture.

Best regards

Ramon

**Comment by RamonFigueras** [comment]
Regarding the behavior of the current configuration of FortiusAnt, If I'm not mistaking the actual setup is for the use of Imagic trainer and, as I own an old Fortius with motor, not magnets, the algorithms to calculate Power and resistance had to be twin. I'm currently working on this. 
Nevertheless the program is usable with both Zwift and Rouvy and Fullgaz even though the resistance is not responding linear to Grade. I replied here to complement the Wouter's one but I believe that this comment deserves an specific issue, so if you don't mind I will open a new issue and copy the comment there

**Comment by WouterJD** [comment]
With having https://fulgaz.com/ mentioned, topic can be closed

**Comment by RamonFigueras** [comment]
Hello Wouter,

Any idea on how to broadcast the FortiusAnt data via Bluetooth FTMS?

Regards,

Ramon

Enviat des del meu dispositiu mòbil 

El 26 març 2020, a les 21:18, WouterJD <notifications@github.com> va escriure:

**Comment by WouterJD** [comment]
Yes: replace the ANT+ interface by Bluetooth.
The advantage would be that a mobile could be used to run Zwift.

Purpose of FortiusANT is to make an old Tacx usable and mission accomplished.

Implementing Bluetooth is not on my bucket-list. Next step will be to support Vortex and Bushido, as soon as owners will present themselves.
