### ISSUE TITLE
T1932 on TacxDesktopApp (TDA)

### ISSUE THREAD

**Issue by Lotze66** [WouterJD/FortiusANT#400]
Hello,
I have installed FortiusANT on Windows 10 notebook and it runs (GUI with detected T1932 and ANT+ dongle is shown). I use a T1932 (blue white) and a Multiplayer Flow T2220. After I connected (2 ANT+ dongle) with TDA, i see the speed and cadence sensors. It is possible to choose a TacxTrainer but only Boost, BlueMagic and other. But they are all show wrong speed or power. I found out that some users use NEO 2T but I don't see it on my list. What is my mistake?

**Comment by WouterJD** [comment]
Welcome to the FortiusANT community
- - -
I'm always curious to know who I communicate with, where FortiusANT is used and what configuration is used.
You already told me what bundle did you buy, and what brake and what head unit do you use.
I would therefore appreciate that you introduce yourself; perhaps leave a comment under issue #14.
You could also consider to visit [the sponsor page](https://github.com/sponsors/WouterJD)
- - -

What CTP do you use (Zwift, rouvy, ...)?
Please share some screens, it may be helpful.

**Comment by WouterJD** [comment]
Since there is no communication here, I assume can be closed.
If not happy to reopen
