### ISSUE TITLE
Installation Problems with Bullseye32 (Installation broken ?) 

### ISSUE THREAD

**Issue by decodeais** [WouterJD/FortiusANT#407]
I wanted to test your new versions.So I thought it would be a good occasion to test your install scripts with the Bullseye release, but I had to do a lot of changes. The greatest problem was the new wheel for wxPython. I put it to
Google Drive and changed the installation Path.
The second problem for me was the broken RollResistance calibration (-c) option on all branches.
I tried to fix it, but then I found out the confusion starts a little deeper.
Tested to change:
self.CalibrateRR = float(self.args.CalibrateRR.replace(',', '.'))
to:
self.CalibrateRR = float(self.args.CalibrateRR.replace(",", "."))
but then I got a Typemismatch instead.
I would like to send you the branch with the Installation changes.
Shall I make a pull request ?

**Comment by decodeais** [comment]
If somebody has Problems too, here is my version with the changes for Bullseye32. May be it can help.
[Branch from FortiusMaster](https://github.com/decodeais/FortiusANT/tree/MasterUpdate)

**Comment by decodeais** [comment]
To get a full working version I took a Backup from my Computer with:
Bullseye32 OS
Bluetooth realized with node
Working pathtthrough for ANT+ heart rate to Bluetooth.
...

I put it  on a googledrive to help other people who have the same problem : [Raspi image with preinstalled FortiusAnt](https://drive.google.com/file/d/16I5dgS1ktXFWj3ml6GYQgdczwVlH_RF8/view?usp=share_link).
The size of compressed selfexpanding  image is only 2.9GB. 
User is Pi
Password raspberry 
If you have a different ANT+ stick you have to change the USB ID-number.
You can start FortiusAnt with the usual start menu.

Here I will stop with the monolog and wait for the response.

**Comment by WouterJD** [comment]
> self.CalibrateRR = float(self.args.CalibrateRR.replace(',', '.'))
```

        if self.args.CalibrateRR != None:
            try:
                self.CalibrateRR = float(self.args.CalibrateRR.replace(',', '.'))
            except:
                logfile.Console('Command line error; -c incorrect calibration of Rolling Resistance=%s' % self.args.CalibrateRR)


```

Please explain what the problem is with this statement.
It first replaces comma's in the string with dots and then converts to float
If this fails for whatever reason, an error is given


Please add the errors that are given

**Comment by decodeais** [comment]
The ' has to be " in the replace command, I think. But the software is waiting for a integer and so it does not work at all. Please try to enter this parameter.
If you succeed send me a command line example in your response.

**Comment by WouterJD** [comment]
I think this is an inconsistency indeed and is subject for further investigation.

-c is to calibrate the RollingResistance
A value from 0...100 is allowed
The value is converted to float
The RollingResistance is a figure of 0.004 default

I leave that for a future moment for now.

**Comment by WouterJD** [comment]
Is there a specific reason you need to adjust the RR?

**Comment by WouterJD** [comment]
I have installed some rpi's tonight and things seem to work well.
If problems persist, please let me know and we can reopen the issue
