### ISSUE TITLE
Used Tacx T1941 Motor Missing Power Back

### ISSUE THREAD

**Issue by shawnventi** [WouterJD/FortiusANT#411]
I just picked up a used Tacx system however it is missing the controls side of the hardware. I basically only have the frame and motor which seems to be in good condition.

![PXL_20230113_220202781](https://user-images.githubusercontent.com/12300328/212427569-8a9f02b0-96a9-4426-993c-03e84cde5444.jpg)

Does anyone know of any hardware hacks to back the use of this motor with a different controller?

**Comment by WouterJD** [comment]
Hi @shawnventi 
Welcome to the FortiusANT community
- - -
I'm always curious to know who I communicate with, where FortiusANT is used and what configuration is used.
Please tell me what bundle did you buy, and what brake and what head unit do you use?
I would therefore appreciate that you introduce yourself; perhaps leave a comment under issue #14.
You could also consider to visit [the sponsor page](https://github.com/sponsors/WouterJD)
- - -

Now back to your question.

The Tacx Fortius consists of:
- frame
- brake
- power unit
- cadense sensor
- headunit with USB connector
A lot of info can be found on: https://github.com/totalreverse/ttyT1941/wiki


The best you did is buy a 2nd hand set, for example https://www.marktplaats.nl/v/sport-en-fitness/wielrennen/m1931160323-tacx-fortius-fietstrainer. As you see available for EUR 25,=.
UNless you really like to re-engineer a Tacx trainer I would buy a working set.

**Comment by WouterJD** [comment]
Since there is no communication here, I assume can be closed.
If not happy to reopen
