### ISSUE TITLE
Ideas related to the virtual gearbox

### ISSUE THREAD

**Issue by szczurem** [WouterJD/FortiusANT#413]
I have two ideas related to the virtual gearbox that should be relatively easy to implement:
1. To have virtual gearbox influence reported TacxTrainer.SpeedKmh (or is it TacxTrainer.VirtualSpeedKmh?). While Zwift or Rouvy does not care (they calculate speed themselves based on power, etc), Garmin does. It is a minor annoyance to have too much mileage rack up on Garmin .fit files (you can correct them afterwards), but annoyance nevertheless. Also, crazy speed records need to be cancelled etc.

2. To report effective gearing via separate ANT+ channel. Garmin computers have the ability to display and record gears selected (eg from Shimano Di2). It could be cool to see how low we had to go while climbing virtual Muro di Sormano. It would be a more tricky modification than the point above, requiring explicit information on the physical gear selected on the bike, translating ReductionCassetteX variable to cogs, etc. For those of us who train using just single gear on the bike and virtual gears it could be simple enough though.

**Comment by WouterJD** [comment]
Great ideas.
I'm very low on time these days, so will not start development soon.
