### ISSUE TITLE
Bluetooth interface cannot be opened; module 'logfile' has no attribute 'fLogfile'

### ISSUE THREAD

**Issue by sylvesterpious** [WouterJD/FortiusANT#423]
Bluetooth interface is not starting with the following error on the GUI.

Using Dynastream Innovations dongle, Bluetooth interface cannot be opened; module 'logfile' has no attribute 'fLogfile'

This is being used on a Macbook with a ANT+ dongle connected to USB. Trying to connect to a Bushido using ANT+ (this works), the bluetooth for use with a CTP doesnt work.

This is with -b mode on. -bb shows an error as well about a assertion failure. 

2023-03-08 05:41:09.453 Python[10149:64938] *** Assertion failure in -[CBPeripheralManager addService:], CBPeripheralManager.m:438
05:41:09,453: clsBleServer._Server(); start() exception NSInternalInconsistencyException - Characteristics with cached values must be read-only
05:41:09,453: , Bluetooth interface n/a; Check exception.

<img width="1473" alt="Screenshot 2023-03-08 at 5 35 49 AM" src="https://user-images.githubusercontent.com/6136013/223518145-27b7a7a0-be85-40f8-a8f3-3656d9d31684.png">

**Comment by WouterJD** [comment]
Sorry for this, is solved in the current branch which will be fully integrated soon.
