### ISSUE TITLE
Tacx head unit returns insufficient data (raspberry slow)

### ISSUE THREAD

**Issue by WouterJD** [WouterJD/FortiusANT#425]
`~/FortiusANT/raspberry/FortiusAntMain.sh -a -bb -Odisplay -e -p25 -D-1 -H-1`
- start automatic
- BLE/bless
- digital display
- excercise bike at 25%
- No ANT dongle
- No Heartrate monitor

FortiusAnt on raspberry is working fine, but sometimes when:
- in another window, the Enter key is pressed repeatedly...
- or a VNC-client on a smartphone connects

**The message "Tacx head unit returns insufficient data" is displayed.**
And when the Enter is is released (or the VNC connection is made), FortiusAnt turns back to normal operation

The message "Tacx head unit returns insufficient data" may therefore also be caused by the Raspberry where FortiusAnt is running. (Not only the headunit being too slow to respond).

Who has experience with this issue
How could this situation be detected
Or even better: avoided?

[Python code](https://github.com/WouterJD/FortiusANT/blob/master/pythoncode/usbTrainer.py#L2480)

---
Hardware info
---
processor	: 0
model name	: ARMv6-compatible processor rev 7 (v6l)
BogoMIPS	: 997.08
Features	: half thumb fastmult vfp edsp java tls 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xb76
CPU revision	: 7

Hardware	: BCM2835
Revision	: 9000c1
Serial		: 0000000040827e00
Model		: Raspberry Pi Zero W Rev 1.1

---
Software info
---
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

Kernel = Linux rpiErica 5.10.63+ #1496 Wed Dec 1 15:57:05 GMT 2021 armv6l GNU/Linux
Debian = 10.13

**Comment by WouterJD** [comment]
Interesting; this does not happen in the calibration loop

**Comment by WouterJD** [comment]
This problem occurs when -b (BLE/Nodejs) or -bb (BLE/bless) is activated.

It seems that the raspberry is not fast enough to do all that work.
Why it affects the USB-interface to the Tacx-trainer is not clear to me.

**Comment by WouterJD** [comment]
Anybody still experiencing this problem?
If not, I will close the issue.

**Comment by MeanHat** [comment]
Happy to close Wouter
