### ISSUE TITLE
Probleme de vitesse avec [speed problem with] kinomap

### ISSUE THREAD

**Issue by regis65** [WouterJD/FortiusANT#427]
Bonjour,j ai mis la nouvelle version la 6.7 et j ai toujours le même problème la vitesse et le dénivelé n est pas la même que sur kinomap,
Voir photo:
![20230319_144250](https://user-images.githubusercontent.com/65114605/226190285-23d99e1c-db6b-436d-8747-7c407bbd9c32.jpg)
![Screenshot_20230319-144158_Kinomap](https://user-images.githubusercontent.com/65114605/226190289-2a5303bf-b416-4388-bd7e-effd4f27cf0c.jpg)
Sportivement

**Comment by WouterJD** [comment]
@regis65 bonjour. Tu utilise toujours le Fortius avec T1932 headunit? Quel moteur/frein (T1942??)

**Comment by WouterJD** [comment]
+ Tu me peu envoyer une imprime de l'écran noir (console); est-ce-quíl-y-a des messages?

**Comment by WouterJD** [comment]
_Looking at your screen; Kinomap asks you to cycle -30%. It's quite steep!_
_You're going 91 rpm and that produces 52 watts, bringing the speed to 112 km/h. It's not surprising._
_But -30% is not realistic._
_Rouvy has the same problem and that's why the -G parameter was introduced._

_Manual page 42:_


---
Regardant ton écran; Kinomap te demande de cycler -30%. C'est assez raide !
Vous roulez à 91 tr/min et cela produit 52 watts, ce qui porte la vitesse à 112 km/h. Ce n'est pas surprenant.
Mais -30% n'est pas réaliste.
Rouvy a la mêmem problème et c'est pourquoi le paramètre -G a été introduit.

Manuel page 42:

-G valeur Modifier la note demandée avec un facteur/factorDownhill ; voir section 6.4 "PowerCurve pour i-Flow (T1901-T1932)". Notez que GradeAdjust n'est pas actif en mode manuel.
FortiusAnt -a -g --> la valeur par défaut : targetGrade = 100 % de la note demandée
FortiusAnt -a -g -G50 --> recommandé lors de l'utilisation de Rouvy : targetGrade = 50 %
FortiusAnt -a -g -G50/50 --> targetGrade = 50% (en montée) et 25% en descente (50% * 50%)
FortiusAnt -a -g -G100/0 --> targetGrade = montée uniquement (remplace l'ancien drapeau -u)
FortiusAnt -a -g -G0/0 --> targetGrade = toujours plat

**Comment by regis65** [comment]
Salut je t envoie l ecran noir
![Uploading 20230322_184121.jpg…]()

**Comment by regis65** [comment]
Salut,je t envoie les photos de l ecran noir
![20230322_183840](https://user-images.githubusercontent.com/65114605/226992151-c01be458-b1f8-4ff3-8450-451ff176c563.jpg)

![20230322_184121](https://user-images.githubusercontent.com/65114605/226992093-3d638cfe-15ec-49c3-8a92-4e01b22e94ba.jpg)

**Comment by regis65** [comment]
Salut,wouter je t es envoyé les photos de l ecran noir sur Github.
Sportivement
Regis

Le lun. 20 mars 2023 à 13:51, Wouter Dubbeldam ***@***.***> a
écrit :

**Comment by WouterJD** [comment]
Merci Regis.
j'ai vue les photos; pas des messages inquiétant.

Alors je reste avec la raccomndation de essayer avec -G

**Comment by regis65** [comment]
Comment fais t on pour le changer

**Comment by WouterJD** [comment]
Aussi dans le GUI tu peut changer le parameter - G
Regarder le manuel
Peut etre cest meux de demander un ami pour aider et Faire les expwrimwnts

**Comment by regis65** [comment]
Salut, tu pourrais m'envoyer le manuel svp.
Merci
Regis

Le dim. 26 mars 2023 à 14:04, Wouter Dubbeldam ***@***.***> a
écrit :

**Comment by regis65** [comment]
Je connais personne qui pourrait me le modifier.

Le dim. 26 mars 2023 à 15:01, Regis Crouzil ***@***.***> a
écrit :

**Comment by WouterJD** [comment]
Parce que c'est toi!

![image](https://user-images.githubusercontent.com/47486941/227783101-5aa04432-8e29-4ec4-baa8-45efcfe783d1.png)

Cliquer sur 
![image](https://user-images.githubusercontent.com/47486941/227783133-66173424-b5e1-4799-913c-224bfa1c0010.png)

![image](https://user-images.githubusercontent.com/47486941/227783197-7bf28c49-6b18-463f-b66a-235d60062fa5.png)

"Modifier la note demandée avec un facteur/facteur en descente (-G)"


Normalement 100% / 100%; dans ton cas tu pourrait specifier 100/10, et ça signifie que -quand kinomap demande une descente de -30%, FortiusAnt línterprete come -3%.

PS. Le manuel en englais se trouve a: https://github.com/WouterJD/FortiusANT/blob/master/doc/FortiusANTUserManual.pdf

Succes!

**Comment by regis65** [comment]
Salut,je l es réglé c est toujours pareil au niveau des kilomètres heures je suis a 50 sur fortius et sur kinomap je suis 12 kilomètres heures .

**Comment by WouterJD** [comment]
FortiusAnt montare la vitesse de la rouw.
Kinomap calcule la vitesse, basé sur power e grade.

C'è Sint deux ciffres completament different

**Comment by WouterJD** [comment]
@regis65 laisse-moi savoir ci s'est claire maintenant

**Comment by WouterJD** [comment]
Since there is no communication here, I assume can be closed.
If not happy to reopen

**Comment by regis65** [comment]
Salut,
Sa fonctionne toujours mal avec kinomap,j ai plus de dénivelé  les
kilometre son pas les mêmes sur kinomap et ton application je ne sais pas
quoi faire,sa m embête d en acheter  un nouveau .
Sportivement
Regis



Le mar. 11 avr. 2023 à 21:21, Wouter Dubbeldam ***@***.***> a
écrit :

**Comment by regis65** [comment]
Salut,
Sa fonctionne toujours mal avec kinomap,j ai plus de dénivelé  les kilometre son pas les mêmes sur kinomap et ton application je ne sais pas quoi faire,sa m embête d en acheter  un nouveau.
Sportivement 
Régis

**Comment by WouterJD** [comment]
FortiusAnt fournit puissance et cadence à kinomap.  Kinomap traduit cela en vitesse.  Cette vitesse n'a aucun rapport avec la vitesse de la roue (la vitesse affichée dans FortiusAnt).  Alors ne t'en fais pas

**Comment by WouterJD** [comment]
Kinomap fournit à FortiusAnt un pourcentage de pente sur la base duquel la résistance est calculée.  Vous pouvez influencer cela avec les paramètres (-G).

**Comment by WouterJD** [comment]
Je lai ecrit april2, puis no response. Maintenant meme question. Questeque tu attend de ma part

**Comment by regis65** [comment]
Moi je pensais que l home trainer et l aplication (kinomap)aurait la même
vitesse,et quand la vidéo montre u dénivelé l aplication (fortiusant)montre
le même dénivelé

Le dim. 14 mai 2023 à 20:02, Wouter Dubbeldam ***@***.***> a
écrit :

**Comment by WouterJD** [comment]
FortiusAnt: vitesse = vitesse de la roue
Kinomap, Zwift, rouvy...: vitesse = f (power, degree, weight)

**Comment by regis65** [comment]
Désolé, je n es pas compris

Le dim. 14 mai 2023 à 20:19, Wouter Dubbeldam ***@***.***> a
écrit :

**Comment by WouterJD** [comment]
Ignorez la vitesse affichée par FortiusAnt et commencez à vous entraîner !
