### ISSUE TITLE
Genius: No Tacx trainer found

### ISSUE THREAD

**Issue by ProYoran** [WouterJD/FortiusANT#432]
Hallo, ik ben Yoran Krol en kom uit Noord-Brabant. Ik heb een Tacx Genius gekocht en 2 ANT+ dongles. Ik wil de software met 1 pc gebruiken.

Als ik FortiusAnt (gui, Genius, autostart).bat open en op "Locate HW" klik, staat er "No Tacx trainer found".

Wat is het probleem?

**Comment by WouterJD** [comment]
Om de tacx Genius te laten werken moet je FortiusAnt vertellen dat het zo'n machine is; dat wordt niet automatisch gedetecteerd.

Zie manual https://github.com/WouterJD/FortiusANT/blob/master/doc/FortiusANTUserManual.pdf, pagina 55.

Start FortiusAnt met **-t Genius** of selecteer dat trainer type in de instellingen, zie hoofdstuk 4.3 op pagina 45.

Succes en anders hoor ik van je.

**Comment by WouterJD** [comment]
> Dat had ik al gedaan.

Da's mooi.
Ik heb toch de indruk dat FortiusAnt op zoek gaat naar een Tacx trainer die via een USB-kabel is aangesloten en dat is toch bij jouw trainer NIET het geval?

"No Tacx trainer found" is een bericht dat hoort bij de USB-aangesloten trainer.
Bij de Genius verwacht ik berichten als "Pair with Tacx Genius", "Tacx Genius paired: %d", ...

Door FortiusAnt te starten met `-d f` of zelfs `-d all` krijg je meer berichten op het console en in de logfile; succes - zou moeten lukken!

**Comment by ProYoran** [comment]
Na herstart is het gelukt, ik weet alleen niet hoe ik resistance krijg. Die voel ik niet.

**Comment by WouterJD** [comment]
Vertel wat meer ;
Welke CTP gebruik je
Wat zie je op FortiusAnt
Wat zie je op je CTP

**Comment by WouterJD** [comment]
Since there is no communication here, I assume can be closed.
If not happy to reopen
