### ISSUE TITLE
Specify ANT dongle windows

### ISSUE THREAD

**Issue by TacxBiker** [WouterJD/FortiusANT#438]
Hi,

Just a question, is it possible to specify the used ANT dongle for FortiusANT?

I use the fortius ANT.exe (latest version) and 2 ANT dongles on one system. If it is possible to specify the used dongle, I think Wahoo Systm will work.
For now I have to use a specified startup procedure to let it all work. 
1. One ANT dongle plugged in
2. start fortiusANT
3. let the program start, calibrate, wait until everything is ready
4. start Wahoo systm 
5. choose a training
6. on that moment there isn't a connection, no free ANT dongle
7. plug in the second ANT dongle and wait untill everything is paired

This works fine if I choose only one training. If I stop the training or something else fails, I have to run the procedure again.

II'd like to specify the used dongle in FortiusANT so Wahoo can use the other one.
Fortius ANT on the Cycplus ANT dongle and Wahoo on the dynastream

thanks,

Mathijs

**Comment by WouterJD** [comment]
Hi Mathijs

I think you can use -D (see manual 4.2 page 43) to select the dongle-type.
I hope you have two different dongles.

I am quite sure that FortiusAnt will never connect to two dongles, so I do not understand why selecting a specific one would work.
Please check that no other ANT-aware software is running, for example Garmin Express.

**Comment by TacxBiker** [comment]
Hi Wouter,

Thanks or your answer. Do these ANT ID's also work in a windows enviorment? I can't find those ID's in the device panel.

**Comment by WouterJD** [comment]
There is no difference in behaviour between the platforms, so yes it works for windows.

The device-ID's are mentioned in the manual (-D value	Select one specific antDongle (perhaps with a non-standard deviceID). The following types are known: 4104 = Suunto, 4105 = Garmin, 4100 = Older. -1 means: no ANT.)

The type of dongle you use is displayed in the windows interface: "Using XXX dongle" where XXX is Suunto, Garmin, ...

Succes!

**Comment by TacxBiker** [comment]
Thanks, will try.

**Comment by WouterJD** [comment]
Since there is no communication here, I assume can be closed.
If not happy to reopen
