### ISSUE TITLE
the gui does not start

### ISSUE THREAD

**Issue by V10l4t0r** [WouterJD/FortiusANT#44]
[Nuovo.Documento.di.Microsoft.Office.Word.pdf](https://github.com/WouterJD/FortiusANT/files/4442473/Nuovo.Documento.di.Microsoft.Office.Word.pdf)

hello I managed to run Antifier which is an old version, with Fortius ANT I'm stuck here.

**Comment by WouterJD** [comment]
Good day!

For some reason, I cannot download the attached pdf.
If the GUI does not start, you probably did not specify the -g flag.
Please refer to https://github.com/WouterJD/FortiusANT/wiki#command-line

Welcome and thanks for using FortiusANT; where are you from?

**Comment by V10l4t0r** [comment]
Thanks, I'm Italian, I'll try to take a look

**Comment by WouterJD** [comment]
Benvenuti sul progetto!

**Comment by V10l4t0r** [comment]
Hi I was lucky because the roller was given to me only because they could not use it with zwift etc. Thanks to you and this project I can use my bike in this period of quarantine at home.

**Comment by WouterJD** [comment]
I hope everything is going well with you and family; if you use strava -  please give me a ping there: https://www.strava.com/athletes/2885978

Buona pedalata!

**Comment by WouterJD** [comment]
What Tacx do you use? Fortius/iMagic? 1902, 1904, 1932, 1942?

**Comment by V10l4t0r** [comment]
> What Tacx do you use? Fortius/iMagic? 1902, 1904, 1932, 1942?

Tacx I-flow T1932 .
ps: 
thanks for adding me on strava

**Comment by WouterJD** [comment]
Thanks. Great fun to see you using FortiusANT.
What training-software do you use?

**Comment by V10l4t0r** [comment]
> Thanks. Great fun to see you using FortiusANT.
> What training-software do you use?


I'm trying zwift, in addition to what I wrote above I add that as sensors I use the cadence sensor and HR sensor of the garmin 530, today I will also put the speed sensor on the rear wheel to get more precise data

**Comment by V10l4t0r** [comment]
> Good day!
> 
> If the GUI does not start, you probably did not specify the -g flag.
> Please refer to https://github.com/WouterJD/FortiusANT/wiki#command-line
> 
> Welcome and thanks for using FortiusANT; where are you from?


I'm looking at your guide, but under windows I can't put those commands, the problem is that by starting FortiusANT.exe the calibration never ends.

**Comment by WouterJD** [comment]
Please check https://github.com/WouterJD/FortiusANT/blob/master/supportfiles/FortiusAnt.bat

Download that file and put it in the same folder where FortiusANT.exe is located.
The file contains some examples of a command-line.

For you "FortiusAnt.exe -g -a" will do the job.

When calibrating starts, you must move the pedal and then calibration actually starts.
Sorry that this is not guided well on the user-interface, I could improve there.

The Tacx then starts calibrating automatically and will stop when the calibration has become stable.

You can also stop calibration with the Cancel button on the console.

**Comment by WouterJD** [comment]
If you do NOT want calibration, specify the -n flag on the command line

FortiusAnt.exe -g -a -n

**Comment by V10l4t0r** [comment]
![IMG_20200407_190534](https://user-images.githubusercontent.com/63247432/78699319-f9bd0a80-7903-11ea-92fd-52cfb07ac787.jpg)

hello I managed to start the program in gui mode, the problem is to do the calibration otherwise during the zwift session the data is very altered.I just finished a session but I had to use the old Antifier version.I have attached the screen of the problema.Ciao

ps: I tried to do the calibration but the roller goes too hard

**Comment by WouterJD** [comment]
I will check

**Comment by WouterJD** [comment]
The special thing is that you have an iFlow which returns the same ID (1932) as the Fortius.
The Fortius supports calibration, but the iFlow seems not.

You can disable calibration by changeing the FortiusANT.bat file and specify the followig command:
`FortiusAnt.exe -g -a -n`
where -n stands for "no calibration"

**Comment by V10l4t0r** [comment]
> The special thing is that you have an iFlow which returns the same ID (1932) as the Fortius.
> The Fortius supports calibration, but the iFlow seems not.
> 
> You can disable calibration by changeing the FortiusANT.bat file and specify the followig command:
> `FortiusAnt.exe -g -a -n`
> where -n stands for "no calibration"

Just to ask, how long does the calibration usually take? With the Antifier program it takes a few seconds; with this I cycled for about 5 minutes but it was very difficult to keep the watts fixed, already at 19/20 km / h it expressed more than 200 watts

**Comment by WouterJD** [comment]
Hi gianluca, good morning.

As far as I know, the antifier program does not do a technical calibration but provides the runoff option.
The calibration as implemented in FortiusANT sends the calibrate command to the roller. The roller then starts spinning (at 20 km/h) and measures the resistance. As soon as the resistance is stable the calibration stops.
The steps are:
- start clibration by moving the pedals down (you do not need to cycle)
- the roller rotates autonomously (you do not need to do anything)
- FortiusANT stops and goes to normal mode

Please execute a test and send the logfile, adding the -d 127 option to the command line.

It may be that your setup (iFlow/1932) does not support this method and then the -n flag can be used to skip the calibration.


I am working on the crash in the runoff part of FortiusANT (already solved).
I am working on improvement on the messaging around calibration (under test now).

Please allow some time and I will upload a new FortiusANT.exe, to be expected these days.

Thanks for working together to improve FortiusANT for iFlow users.

**Comment by WouterJD** [comment]
Version 2.5 is uploaded (exe only); please test

**Comment by V10l4t0r** [comment]
> Hi gianluca, good morning.
> 
> As far as I know, the antifier program does not do a technical calibration but provides the runoff option.
> The calibration as implemented in FortiusANT sends the calibrate command to the roller. The roller then starts spinning (at 20 km/h) and measures the resistance. As soon as the resistance is stable the calibration stops.
> The steps are:
> 
> * start clibration by moving the pedals down (you do not need to cycle)
> * the roller rotates autonomously (you do not need to do anything)
> * FortiusANT stops and goes to normal mode
> 
> Please execute a test and send the logfile, adding the -d 127 option to the command line.
> 
> It may be that your setup (iFlow/1932) does not support this method and then the -n flag can be used to skip the calibration.
> 
> I am working on the crash in the runoff part of FortiusANT (already solved).
> I am working on improvement on the messaging around calibration (under test now).
> 
> Please allow some time and I will upload a new FortiusANT.exe, to be expected these days.
> 
> Thanks for working together to improve FortiusANT for iFlow users.

thank you so much for dedicating your time to this project, I will try the new executable soon. Thanks for the explanation on the calibration.

**Comment by V10l4t0r** [comment]
[FortiusANT.2020-04-08 14-34-17.log](https://github.com/WouterJD/FortiusANT/files/4451123/FortiusANT.2020-04-08.14-34-17.log)
Good afternoon, I performed the test with the new executable regarding the calibration without subsess. Now I will try to do a session on zwift skypping the calibration to see how it goes with the new exe

**Comment by WouterJD** [comment]
From the logfile it seems that calibration does not work in your situation; the returned resistance is constant.

The calibration stops when the resistance remains constant for some time and will stop after 8 minutes. My Fortius returns a negative value during the calibration and it seems your system returns a positive value.
I will check this and detect the situation.

You may keep this issue open untill it's really solved; I prefer that the software fits your iFlow as well as the others.

Success with zwift tonite!

**Comment by V10l4t0r** [comment]
[FortiusANT.2020-04-08 16-17-08.log](https://github.com/WouterJD/FortiusANT/files/4451639/FortiusANT.2020-04-08.16-17-08.log)
hello, just to be exact I did the calibration test again waiting 10 min. The roller does not move by itself. Probably this function is not there; in this regard, I remember that not even in the original tacx software did an automatic calibration. It was necessary to make a sort of runoff and depending on the data that came out on a graph it was necessary to tighten or loosen a lever. Now what I think is the real problem is that in the zwift program the power does not work well.

**Comment by BikeBeppe64** [comment]
Hi WJD, 
Beppe from Italy just to confirm GUI v2.6 works with T1932 as picture shows. As soon as possible I will do other tests.
Regards

![IMG_20200508_012320](https://user-images.githubusercontent.com/64853498/81354368-b0f79d80-90cb-11ea-84b3-cc3e08f9383c.jpg)

**Comment by WouterJD** [comment]
Buon "giorno"! Benvenuto. Da dove sei?
Saluti della Olanda!

**Comment by BikeBeppe64** [comment]
Milano, Lombardia, Italy
Windows 10, Antifier & Garmin USB used
I-Flow VR T2250 new
Also Garmin Vector 2s (powermeter)

**Comment by WouterJD** [comment]
Greate Beppe, see you later
