### ISSUE TITLE
ANT Dongle not available

### ISSUE THREAD

**Issue by smartes** [WouterJD/FortiusANT#444]
Hello,
I try to start an old Tacx Trainer. I have 2 ANT dongles (Dynastream Innovations, Inc. ANTUSB2 Stick). I downloaded (and seems) installed ForiusANT on Ubuntu system.  When FortiusANT started I got 

```
Connected to Tacx Trainer T1932
Motor Brake Unit Firmware=0x1007 Serial=  716 year=2009 type=T1941 Version2=2842 MotorBrake=True
FortiusAnt applies the MotorBrake power curve
FortiusANT broadcasts data as an ANT+ Controlled Fitness Equipent device (FE-C), id=57591
FortiusANT broadcasts data as an ANT+ Heart Rate Monitor (HRM), id=57592
FortiusANT broadcasts data as an ANT+ Bicycle Power Sensor (PWR), id=57596
FortiusANT broadcasts data as an ANT+ Speed and Cadence Sensor (SCS), id=57595
FortiusANT receives commands from an ANT+ Generic Remote Control
---------- ANT- and BLE-devices are activated ----------

```
After Pedal Stroke calibration I start GoldenCheetah and try to connect them together. However, in FortiusANT terminal I get an error message
`ANT Dongle not available; try to reconnect after 1 second`
`AntDongle.Write exception (message lost): [Errno 5] Input/Output Error`

In turn, GoldenCheetah doesnt see any equipment.

**Comment by WouterJD** [comment]
Welcome to the FortiusANT community
- - -
I'm always curious to know who I communicate with, where FortiusANT is used and what configuration is used.
Please tell me what bundle did you buy, and what brake and what head unit do you use?
I would therefore appreciate that you introduce yourself; perhaps leave a comment under issue #14.
You could also consider to visit [the sponsor page](https://github.com/sponsors/WouterJD)
- - -

Please read issue #61 to see if that applies.
If that does not help, please let me know to check further,

**Comment by WouterJD** [comment]
Since there is no communication here, I assume can be closed.
If not happy to reopen
