### ISSUE TITLE
Support I-Vortex T1960, trainer niet gevonden

### ISSUE THREAD

**Issue by Rien1980** [WouterJD/FortiusANT#445]
Hoi Wouter,

Om te kunnen trainen voor de Alpe d'HuZes heb ik een I-Vortex T1960 met T2160 computer in gebruik. Ik krijg deze echter niet aan de praat met Fortius ANT. Als ik de ANT dongle aansluit wordt deze herkend. De trainer zelf wordt echter niet gevonden. 

Groet,

Rien

**Comment by WouterJD** [comment]
Welkom in de FortiusANT community
- - -
Ik ben altijd nieuwsgierig met wie ik communiceer, waar FortiusANT wordt gebruikt en in welke configuratie.
Welke bundle heb je gekocht, en welke rem en head-unit gebruik je?
Vertel meer over jezelf, eventueel onder issue #14.
- - -

Het eerste advies is om FortiusAnt op te started met de `-t vortex `parameter, zodat bekend is welk type trainer gezocht moet worden.

**Comment by WouterJD** [comment]
Hi Rien, welcome again. 

> My ANT-dongle is recognized as you can see below.

Did you attach something, I don't see it😬

Mind that you have to tell FortiusAnt to look for the vortex with the `-t vortex ` parameter

**Comment by WouterJD** [comment]
`-t vortex ` specified?

**Comment by GewoonGijs** [comment]
Hoi Rien, als je het niet werkend krijgt, mag je mijn werkende setup overnemen. Die bestaat uit een Fortius met een raspberry pi. Verbinding met je PC/laptop over Bluetooth. 

Voor €75,- mag je het geheel overnemen. Ik ben overgestapt op een direct drive trainer.

**Comment by Rien1980** [comment]
> Referenc



> `-t vortex ` specified?

Yes I did. Doesn't recognize the trainer. I will try with my MacBook also.

**Comment by WouterJD** [comment]
@Rien1980 wanneer je op [Locate HW] drukt, wat gebeurt er dan? Met nadruk op het veld, waar nu "No tacx trainer found" staat.

**Comment by WouterJD** [comment]
Ik verwacht in ieder geval dat bericht "Tacx Vortex paired:...  (pairing can take a minute)"
langs komt.

**Comment by WouterJD** [comment]
![image](https://github.com/WouterJD/FortiusANT/assets/47486941/b3420573-0784-4d31-a0dd-6fcbd1fb6990)

Zie voorgaande scherm
- zie je in het console de opstartparameters? 
- zie je het bericht "Pair with Tacx Vortex ... (pairing can take a minute)"

Heb je geexperimenteerd met het opslaan van de settings in een JSON file?
De settings in de JSON file overrulen de command-l;iine

**Comment by Rien1980** [comment]
Hoi Wouter,

Mijn Tacx gaat aan de stroom, de stuurunit zet ik ook aan. Ik begin dan alvast te trappen. Via USB heb ik de ANT dongle aangesloten aan mijn laptop. Alles staat redelijk dicht bij de unit. Dan start ik FortiusANT vanuit de WindowsExecutable map. In de instellingen zet ik dan Vortex aan. Ook als ik op locate hw klik vindt hij de Vortex niet. 

Groet,

Rien

**Comment by WouterJD** [comment]
Deel even een screen print nadat hij de trainer niet heeft gevonden, waar het FortiusAnt EN het zwarte scherm op te zien zijn aub

**Comment by Rien1980** [comment]
Hoi Wouter,

Bij deze.

![image](https://github.com/WouterJD/FortiusANT/assets/152170026/5a7a6b59-9b8e-480e-8052-9907b739e34f)

Groet,

Rien

**Comment by WouterJD** [comment]
Als je de exe opstart en verder niets hebt gedaan, zoekt FortiusAnt naar een USB trainer.

Er wordt nu NIET naar een vortex trainer gezocht

**Comment by Rien1980** [comment]
Ik heb in de settings aangegeven dat ik een Vortex gebruik.

![image](https://github.com/WouterJD/FortiusANT/assets/152170026/3dcf2151-1c40-4153-9c21-176275f653c1)

**Comment by WouterJD** [comment]
Ik ga vanavond (hoop ik) even kijken

**Comment by WouterJD** [comment]
Rien

Het ziet er naar uit dat je alles goed hebt gedaan, maar dat er met de -t wijziging via het instellingen scherm iets niet werkt.


Start windows verkenner
In de folder **FortiusANT\StartUp** vindt je het opstart script **FortiusAnt (exe).bat**
Klik met de rechtemuisknop op dat bestand en klik op bewerken.
Maar van de eerste regel `..\WindowsExecutable\FortiusAnt.exe -g -t Vortex`
Klik op Bestand, Afsluiten en bewaar het bestand.

Start FortiusAnt door hierop te dubbelklikken

Je ziet dan een scherm als onderstaand:
![image](https://github.com/WouterJD/FortiusANT/assets/47486941/77920334-19e7-4046-8844-de83c262badb)

Klik op [Locate HW] en dan zou je onderstaande moeten zien:
![image](https://github.com/WouterJD/FortiusANT/assets/47486941/bfd120dc-37da-4f62-adea-23c87c5afff1)

Klik dan op [Start], FortiusAnt moet dan naar je trainer gaan zoeken
![image](https://github.com/WouterJD/FortiusANT/assets/47486941/d5f13d65-4540-4598-bee6-00fb3f8f342c)


Ik hoor graag van je en ik ga kijken wat er met de instellingen gebeurt...

**Comment by Rien1980** [comment]
Beste Wouter,

Je bent een held. Hij doet het. Nu nog even klooien met een fietsapp en gaan met de banaan. Ik ga van het weekend helemaal los de Alpe 'd Huez op.

Super dat jij hiermee een bijdrage hebt geleverd aan mijn training. 

https://www.opgevenisgeenoptie.nl/fundraisers/RienVerbeek/alpe-dhuzes

Groet,

Rien

**Comment by WouterJD** [comment]
Top!

Zit je ook op strava? https://www.strava.com/athletes/2885978 Zie je daar!

En als je blij bent met deze Tacx/fietsapp (Zwift?) bridge, kijk dan nog even op de [sponsorpagina](https://github.com/sponsors/WouterJD/).

Succes!

**Comment by Rien1980** [comment]
Hoi Wouter,

Ik heb me op Strava net geconnect met de FortiusAnt groep en heb net in
Paypal een sponsoring gedaan. Ben je zeer dankbaar.

Groet,

Rien

Op vr 8 dec 2023 om 11:57 schreef Wouter Dubbeldam ***@***.***

**Comment by WouterJD** [comment]
Ik hoop dat je d'r plezier mee hebt!
Ik ga binnekort eens kijken waarom de vortex instelling niet werkt. Maar dat voor later.
En al vast bedankt voor de sponsoring.

**Comment by WouterJD** [comment]
When -t is specified interactively, the setting was not effectuated.
Improved in next version.

**Comment by WouterJD** [comment]
> Paypal een sponsoring gedaan. Ben je zeer dankbaar.

Hoi Rien, geen big deal. Maar ik zie dat nog niet in Paypal.

Belangrijker is dat je trainer het doet!

**Comment by WouterJD** [comment]
The user interface is improved and published including EXE in 6.8****
