### ISSUE TITLE
Rouvy issue

### ISSUE THREAD

**Issue by TomX6601** [WouterJD/FortiusANT#455]
from some reason the connection of FortiusANT on Rpi 3B+ to Rouvy on W11 notebook drops after few minutes of the workout.

**Comment by TomX6601** [comment]
It seems, that onboard BLE chipset and as well as recommended BLE domgle Asus BT-400 has the same problem to connect reliably FortiusANT. Currently the only working setup is ZWIFT paired through IPhone. Pairing directly through BT does not work properly, although I can pair FortiusANT in Windows somehow.

**Comment by TomX6601** [comment]
It finds the FortiusAnt, sends 3 BT requests for pairing to Rpi and then says "Device is not possible to connect as a smart trainer"

**Comment by WouterJD** [comment]
It all seems a chipset / driver issue, which I cannot reproduce, not having your configuration.
The FortiusAnt logfiles will (most likely) noty be of any help, because the problem is likely at the lower levels.

**Comment by WouterJD** [comment]
Same as #452

**Comment by TomX6601** [comment]
It suddenly works. No Idea how it happened, but it looks like some Hell in Windows11 :)

**Comment by WouterJD** [comment]
Fortunately, now you can train👍
