### ISSUE TITLE
FortiusANT showed up as HRM in TDA 

### ISSUE THREAD

**Issue by Doncany** [WouterJD/FortiusANT#459]
Hi, tested FortiusANT with my old IFlow trainer on win 10. T1932 Headunit 
Connection an detection works fine all date could displayed in GUI. I would like to use ist with BLE to broadcast to IOS device, but as device it displays a HRM with my PC Name. 

Could my help somebody? Thanks

**Comment by WouterJD** [comment]
Welcome to the FortiusANT community
- - -
I'm always curious to know who I communicate with, where FortiusANT is used and what configuration is used.
Please tell me what bundle did you buy, and what brake and what head unit do you use?
I would therefore appreciate that you introduce yourself; perhaps leave a comment under issue #14.
You could also consider to visit [the sponsor page](https://github.com/sponsors/WouterJD)
- - -
As described on page 16 of the manual
•	FTMS (FiTness Machine Service), receiving target power or grade and sending speed/cadence/power
•	HRS (Heart Rate Service)
so if the HRS is visible, it would be strange that the FTMS is NOT there...

The name of the device is library dependant; the PC-name is normal.

Please give it a second check and let me know.

**Comment by WouterJD** [comment]
Since there is no communication here, I assume can be closed.
If not happy to reopen
