### ISSUE TITLE
Meaning of command line values

### ISSUE THREAD

**Issue by TomX6601** [WouterJD/FortiusANT#462]
Hi,
what mean values shown in command line window (rpi)?
Power, Cadence, speed is clear, but what means r parameter? there is r=27 and when I move it changes to r=203. 
next is 100%. What it means? If I use parameter -p90, there is stil 100%? I am using i-Magic with Rouvy (-G50 as reccommended), but my Favero pedal meter always shows power higher for 10%, so I use -p90 parameter to synchronize it, but I do not know if the FortiusANT accepted it

**Comment by WouterJD** [comment]
Ha, power meter!

I'll answer this q ASAP. OK?

**Comment by WouterJD** [comment]
Target, Speed, Current Power, Cadence will be obvious
r=resistance, the resistance of the motor drive, which results in a target power at a given wheel speed.
The percentage is the virtual gearbox, which initially is 100%
The last parameter are the leds.


-p: Adjust target Power by multiplying by this factor for static calibration.
If the power, displayed by FortiusAnt is always 10% higher than your power-meter, specify -p90 to reduce resistance by 10%.

-c: Calibrate the rolling resistance for magnetic brake.

**Comment by WouterJD** [comment]
To know the accepted values run FortiusAnt with -d1 to activate ddebugging and the parameters are displayed

**Comment by TomX6601** [comment]
thnx
