### ISSUE TITLE
Power curve validation

### ISSUE THREAD

**Issue by TomX6601** [WouterJD/FortiusANT#463]
I have i-Magic 1902 + Rouvy. The trainer breaks more, then it is required. Is it enough to calibrate it by decreasing parameter -c or should I implement some function described in 6.3 section of Manual?

**Comment by WouterJD** [comment]
Hi! Good that you look into this.

How do you know the power isincorrect; feeling or power meter? The latter is a good help.
Write down the differences. Is it a somewhat fixed %, then - c is a solution.

Please note that these legacy trainers should be compared to the modern tacxes. Yes we can connect to modern software, the trainer is "old design and capabilities".

Succes and let me know

**Comment by TomX6601** [comment]
My setup is following:
i-Magic 1902 + FortiusAnt + Rouvy. I have Rouvy connected to TrainingPeaks where I choose the workout. In Rouvy I just connect any video to this workout. On my bike I use Favero power meter connected to Garmin Edge, independently from Rouvy. There was some static difference between Favero and FortiusAnt, so I solve it by -p parameter.It shows correct Power, but workout breaks the trainer too much. I have an idea to calibrate it by -c parameter. Is it correct?

**Comment by WouterJD** [comment]
> workout breaks the trainer too much

Q1: please explain how you know that it's toomuch🤔

---

Rouvy transmits the real value for slope. 10% is received as 10%, whereas Zwift Shows 10% in it's own windows but transmits a lower value.

Real slope percentages cause noticeable resistances. 

You can adjust this in FortiusAnt using the - G parameter, see manual

**Comment by TomX6601** [comment]
Independently I measure power through Favero pedals. Command -c does not work ![image](https://github.com/WouterJD/FortiusANT/assets/70278157/e78a4381-0448-48a7-9994-e951c82d190d)

**Comment by WouterJD** [comment]
I would say -c works, but you have to provide the correct value

**Comment by TomX6601** [comment]
What am I doing wrong? I put there -c 14 or -c14 as decribed on page 42 of Manual and I receive error message "command line error"

**Comment by WouterJD** [comment]
I modified https://github.com/WouterJD/FortiusANT/blob/master/pythoncode/FortiusAntCommand.py#L368
Please retry

Sorry for the inconvenience

**Comment by decodeais** [comment]
Why did you  change FortiusAnt.sh?

**Comment by WouterJD** [comment]
See comment

**Comment by decodeais** [comment]
it looked for me you changed the FortiusAnt.sh script for debugging. it was only a hint. The changes for the -c parameter are ok.

**Comment by TomX6601** [comment]
> I modified https://github.com/WouterJD/FortiusANT/blob/master/pythoncode/FortiusAntCommand.py#L368
> 
> Please retry
> 
> 
> 
> Sorry for the inconvenience
> 
> 
> 
> 

Thnx. It works somehow. It seems, that powercurve is slightly different in low power, like 110W, but still in tollerance I use

**Comment by WouterJD** [comment]
Greate that the issue is sufficiently solved!
