### ISSUE TITLE
tacx 2021

### ISSUE THREAD

**Issue by albon4** [WouterJD/FortiusANT#469]
Hey I recently bought a genius tacx t2021 but ant+ but I don’t why it’s not wanting to connect I have updated drivers and everything pls help I’ve search every where nothing is working

**Comment by albon4** [comment]
i dont understand how to setup the app

**Comment by albon4** [comment]
i just need some guidance

**Comment by WouterJD** [comment]
Welcome to the FortiusANT community
- - -
I'm always curious to know who I communicate with, where FortiusANT is used and what configuration is used.
Please tell me what bundle did you buy, and what brake and what head unit do you use?
I would therefore appreciate that you introduce yourself; perhaps leave a comment under issue #14.
You could also consider to visit [the sponsor page](https://github.com/sponsors/WouterJD)
- - -
I guess you have a genius.
FortiusAnt must be started with the -t genius flag as described in the [manual](https://github.com/WouterJD/FortiusANT/blob/master/doc/FortiusANTUserManual.pdf).

FortiusAnt uses one dongle; connecting to the genius and transmitting standard trainer protocol at the other side (converting the signals).
Zwift (using a second dongle / or on another system) receives the ANT signal and communicates through ForiusAnt with the genius.

Suces.

**Comment by albon4** [comment]
> Welcome to the FortiusANT community
> 
> I'm always curious to know who I communicate with, where FortiusANT is used and what configuration is used. Please tell me what bundle did you buy, and what brake and what head unit do you use? I would therefore appreciate that you introduce yourself; perhaps leave a comment under issue #14. You could also consider to visit [the sponsor page](https://github.com/sponsors/WouterJD)
> 
> I guess you have a genius. FortiusAnt must be started with the -t genius flag as described in the [manual](https://github.com/WouterJD/FortiusANT/blob/master/doc/FortiusANTUserManual.pdf).
> 
> FortiusAnt uses one dongle; connecting to the genius and transmitting standard trainer protocol at the other side (converting the signals). Zwift (using a second dongle / or on another system) receives the ANT signal and communicates through ForiusAnt with the genius.
> 
> Suces.

**Comment by albon4** [comment]
Hey mate what do I do if I don't have a second ant+ dongle

**Comment by WouterJD** [comment]
Every application needs its own dongle.
If you do not have one, buy one.

Alternative: use another system with an ANT-interface, thus realizing the second dongle.

**Comment by WouterJD** [comment]
You wanna have it closed?

**Comment by albon4** [comment]
no

**Comment by albon4** [comment]
Sorry i dont really understand github but i have a question do i need two dongles(ant+)

**Comment by albon4** [comment]
![image](https://github.com/user-attachments/assets/4437eb1b-32ad-4dbd-801c-3668911d83a4)

**Comment by albon4** [comment]
Does this work sir?

**Comment by WouterJD** [comment]
Usually ant ANT dongle works, only the cycplus dongle are know for issues, as documented.

You can start with one dongle to validate the trainer and the interface, using the simulation and manual modes.

Note that I do not have a genius nor ever had, so some experimenting is to be done.

**Comment by albon4** [comment]
![image](https://github.com/user-attachments/assets/df456628-c5da-435d-84e6-0e4884179689)

**Comment by WouterJD** [comment]
How did you start FortiusAnt?
Now use the settings wheel and sect genius as tacx type and retry.

FortiusAnt is not build to detect all possible tacx types, therefore you must tell what type to look for

**Comment by albon4** [comment]
okay that worked but all i need now is a another ant+ right???

**Comment by albon4** [comment]
or is there an alternative?

**Comment by WouterJD** [comment]
Hey sounds good, please share picture.
Yes, if this the case, a 2nd dongle allows Zwift to run on the same computer, assuming it has enough power

**Comment by WouterJD** [comment]
> Every application needs its own dongle. If you do not have one, buy one.
> 
> Alternative: use another system with an ANT-interface, thus realizing the second dongle.

Read this

**Comment by albon4** [comment]
Okay what do u want picture of, i'm guessing the ant+ i'm ordering?

**Comment by WouterJD** [comment]
No, I believe that.

Your configuration + your setup, if you like.

**Comment by albon4** [comment]
okay ill do that tmrw, great thanks for the help ur really saved me!

**Comment by albon4** [comment]
i have another question u might of told me this but im not sure. But could i use my phone as a second ant+?

**Comment by WouterJD** [comment]
How are things proceeding?

**Comment by WouterJD** [comment]
Since there is no communication here, I assume can be closed.
If not happy to reopen
