### ISSUE TITLE
Support for Data Page 51 - Coefficient of Rolling Resistance

### ISSUE THREAD

**Issue by mattipee** [WouterJD/FortiusANT#56]
Already parsed in page 51, but would like to be able to actually use a non-default received value in the physical calculation of required power in Grade2Power().
Suppose need to check that "use default value" 0xFF is provided by sending system (Zwift/etc..) if unused, or use if present?

**Comment by WouterJD** [comment]
Well, perhaps lazy programming - but I did not see the message coming in and hence ignored the possible existance.

**Comment by mattipee** [comment]
It's a very subtle effect I imagine. I just like the idea of simulating where parameters are provided. I ride on country roads or through the woods, rarely in a velodrome. Again if the software I use doesn't provide it, I may modify, or at the very least specify as a parameter to FortiusANT if not available on ANT+.

**Comment by WouterJD** [comment]
Implemented in https://github.com/WouterJD/FortiusANT/tree/54-usbTrainer

**Comment by WouterJD** [comment]
Implemented in 3.0
