### ISSUE TITLE
Support for Data Page 71 - Command Status

### ISSUE THREAD

**Issue by mattipee** [WouterJD/FortiusANT#63]
Yet to identify controller that uses this, but just as I go through the spec, seems like a sensible thing to cover off or at least record here. No immediate requirement.

**Comment by WouterJD** [comment]
As unlucky as it may be, FortiusANT is derived from antifier and not build from spec.
Page 71 is in the spec and should be there; but no CTP (Trainer Road, Zwift, Rouvy, ...) use it and hence it would be unused code that cannot be tested...

As a product-developer I would close the request with "Left for future improvement"

**Comment by mattipee** [comment]
Any messages can be tested using SimulANT from Garmin.

**Comment by WouterJD** [comment]
The purpose is to use, testing is how to get there.

**Comment by WouterJD** [comment]
msgPage71_CommandStatus implemented in i-Vortex pull request.
Please let me know whether it works.
