### ISSUE TITLE
How many dongles required to use FortiusANT?

### ISSUE THREAD

**Issue by yancart** [WouterJD/FortiusANT#68]
Hi, Id just like to understand a little more about using FortiusANT & zwift.
I currently have a Tacx Fortius trainer connected via the normal USB cable to a win10 laptop and Id like to use it with zwift. If I wanted to run zwift on an ipad I understand I'd need two USBant sticks in the laptop to connect data to the iPad, but do I still need the USBant sticks if zwift is running on the laptop?
Also why two USBant sticks, is that pwr and speed?
And assume this should be 2way if it works correctly and will control the motor to create a gradient?

Thanks

**Comment by mattipee** [comment]
Hi @yancart.

You need a minimum of one ANT+ dongle so that FortiusANT (which speaks to the Fortius over USB) can also speak to "anything-else" over ANT+. So FortiusANT needs one ANT+ dongle.

If you run Zwift on the iPad, you don't need a second ANT+ dongle. on your laptop, just one is all that FortiusAnt needs.

If Zwift is running on the same laptop, I can understand the confusion but here you do need that second ANT+ dongle - Zwift can't talk to the Fortius over USB itself, it needs it's own ANT+ dongle to talk to FortiusANT's ANT+ dongle, which will in turn control the Fortius over USB.

Regards,
Matt.

**Comment by WouterJD** [comment]
Wel spoken, Mat.
@yancart welcom onboard!

https://github.com/WouterJD/FortiusANT/wiki#requirements

**Comment by WouterJD** [comment]
PS @yancart I'm always interested where the FortiusANT users come from, planting a flag on the FortiusANT world. Please sign the #14 page and/or say hello on Strava! https://www.strava.com/athletes/2885978

**Comment by yancart** [comment]
Hi Matt,

Thanks for the reply and helps to explain things.
Just found out zwift only runs on a 64bit pc so its either an ipad or a new laptop.
I assume most USBant devices should work?
Thanks

**Comment by WouterJD** [comment]
Check #61

**Comment by yancart** [comment]
Thanks....

**Comment by WouterJD** [comment]
Try rouvy it's not so demanding on PC hardware
Download the correct one, though check #52

**Comment by yancart** [comment]
Just been looking at the Rouvy link.
So is Rouvy an alternative to FortiusANT.
Its to be installed on win10 pc, does this affect which one I choose?
Thanks

**Comment by WouterJD** [comment]
Rouvy, Trainer Road, Zwift all talk ANT-language to a trainer
Modern trainers talk ANT so can talk with this software

Old trainers talk USB-cable
FortiusANT translates USB-cable to ANT


Trainer <--> FortiusANT <-->[Zwift, Rouvy, Trainer Road]
Therefore answer is No

**Comment by yancart** [comment]
Hi WouterJD, its taken a while but Im now set up with the Tacx Fortius TTS runing on a 64bit win10 laptop, so ready for Zwift.
Do you have the link for your s/w to broadcast the Fortius data through ANT so I can set up the Zwift app?
Thanks

**Comment by WouterJD** [comment]
Hi, long time no see :-)

You do not need a link.
Start FortiusANT and do the calibration if required. Then FortiusANT is ready for use and transmitting ANT-devices.
Start Zwift and do the pairing action; Zwift will report that there is an FE-C device with deviceID 57591; use that one.

Hope this answers the question.

**Comment by yancart** [comment]
Hi Wouter, downloaded FortiusAnt v3.2.1 which runs up ok and seems to find both ANT USB but not the Tacx trainer Fortius h/w?
Tries the locate h/w but nothing happens. If it finds the h/w does the calibration start automatically?
![image](https://user-images.githubusercontent.com/64601681/89105539-dd485f00-d419-11ea-8e46-678f492c5e4a.png)
Checked the Fortius trainer with TTS s/w and all seems fine. 

Also tried ExplorAnt and get a few errors:
![image](https://user-images.githubusercontent.com/64601681/89105642-bb031100-d41a-11ea-9a2a-938e12c5c413.png)
 Does this help explain anything?

Thanks

**Comment by WouterJD** [comment]
First thought: did you install libusb device?

**Comment by yancart** [comment]
Ah no! Just spotted this in your wiki instrutions!
Will follow that through and let you know...

If it finds the h/w does the calibration just start automatically?
And is ExplorAnt just for debugging?
Thanks

**Comment by WouterJD** [comment]
Calibration starts automatically for Fortius and skipped for others
explorANT is for debugging only indeed

**Comment by yancart** [comment]
Just about to install the libusb s/w, but just thought will this still allow the normal Tacx s/w to run as before as the "jungo" device driver will have been replaced by the libusb?

**Comment by WouterJD** [comment]
See #99 
I have no conclusive instruction how to let coexist. I have two systems, one for FortiusANT and the other for TTS. I understand this is luxury...

**Comment by yancart** [comment]
Ah so I think you're saying once I swap the device drivers from jungo to libusb TTS will stop working?

**Comment by WouterJD** [comment]
What I know is that I don't know.
See posts in #99 
You can always swap drivers again

**Comment by yancart** [comment]
Ok thanks will see how it goes...

**Comment by WouterJD** [comment]
libusb is only needed for the USB-cable to a Tacx Fortius (or similar) trainer.
The ANT+ dongles have their own drivers

**Comment by yancart** [comment]
So the libsub driver is only needed for the the Fortius_Unint driver, as in the screenshot above..
Thanks

**Comment by WouterJD** [comment]
Hope this helps
![image](https://user-images.githubusercontent.com/47486941/93430498-0dad6500-f8c3-11ea-84b9-7b0e8332b4ba.png)
