### ISSUE TITLE
Feature suggestion: Transmit PWR profile separately

### ISSUE THREAD

**Issue by tobekas** [WouterJD/FortiusANT#79]
Hi Wouter,
is it possible to transmit Ant+ Device Profile PWR (and maybe S&C) in addition to FE-C?
I tested FortiusANT in simulation mode and tried to pair it with my Edge 800. It could find the HRM channel but unfortunately no power sensor. I think this is because the edge 800 does not support FE-C. However it would be great, if it could be used to track the workout with power information.

**Comment by WouterJD** [comment]
Will do after current developments

**Comment by WouterJD** [comment]
Check in on #87

**Comment by tobekas** [comment]
Do you mean, this feature suggestion will be tracked in #87 or that is should already be implemented in the lated version?
With Version 3.0 a cannot find a separate "ANT+ PWR" channel with my Edge 800 by now. At least not in simulation mode (-s flag).
My original feature suggestion was to additionally broadcast a plain power channel (ANT+ PWR profile) in addition to the FE-E channel, which already includes power. Or even beyond that to additionally broadcast the S&C channel (speed and cadence), if possible.

**Comment by WouterJD** [comment]
Hi @tobekas Thanks for responding.

I sure understood your request and from #87 I understand that Edge pairs with FE-C channel.
First step please check what's going on in #87.
I have no edge so cannot test that.

If edge does not pair, I'm happy to create PWR profile; in that case please reopen this issue.

**Comment by tobekas** [comment]
Edge 820 does pair with FE-C but Edge 800 and some other old generation devices don’t. In #87 it’s about pairing with an Edge 820. He also mentions an 800, but this is used as a reference measurement paired with an independent power meter and speed sensor for comparison.

My suggestion is to add PWR profile, to enable pairing with older devices. As far as I know, new generation Smart Trainers also provide PWR in addition to FE-C. 

In addition to using Swift..., this would also make it possible to simply record power data with the Edge (for workout history in garminConnect, Strava...) during boring training only with the head unit, in case you don't have a power meter on your bike.

**Comment by WouterJD** [comment]
ok

**Comment by WouterJD** [comment]
@tobekas SCS and PWR profile are ready for test; refer to https://github.com/WouterJD/FortiusANT/pull/95.

**Comment by tobekas** [comment]
Hi. Just tested your branch (in simulation mode) and it works like a charm. SCS and PWR Sensors now appear and can be paired with my Edge 800. Great!

**Comment by WouterJD** [comment]
Great, thanks for testing👍👍

**Comment by WouterJD** [comment]
Implemented

**Comment by BikeBeppe64** [comment]
> Hi. Just tested your branch (in simulation mode) and it works like a charm. SCS and PWR Sensors now appear and can be paired with my Edge 800. Great!

I did It in a simulation mode too but had problem in normal mode.
