### ISSUE TITLE
Problèmes avec l'installation - In French

### ISSUE THREAD

**Issue by regis65** [WouterJD/FortiusANT#83]
Bonjour,
J ai essaye d installé FortiusAnt sur mon pc mais je n y arrive pas j ai lu les instruction et sa fonctionne pas 
Mon home trainer Tacx Fortius
Mon pc windows 10
Hp i5 
6Go ram
Carte Graphique 2go
Pouvez m aider merci

**Comment by WouterJD** [comment]
"J ai essaye d installé FortiusAnt sur mon pc mais je n y arrive pas j ai lu les instruction et sa fonctionne pas"

Please provide more information; what happens, what error-code is given?

**Comment by regis65** [comment]
Salut,
en fait j essaye d installer le nouveau driver sur Vr interface il veux ce change

**Comment by WouterJD** [comment]
Regis
Pour vous pouvoir aider j'ai besoin de plus informations.
- Quel actions vous faites
- Quel reponses, message du système

Voyez le page wiki pour informations sur installer é desinstaller les drivers de Tacx: https://github.com/WouterJD/FortiusANT/wiki#windows

**Comment by regis65** [comment]
bonjour 
j ai reçu a l installer sur un pc de 32 bits sa a l air de fonctionner mais le souci c est que j ai les kilomètres,cadence........ directement sur la page noire et il normal ?

**Comment by WouterJD** [comment]
Oui c'est normal, vous n'avez pas specifié des paramètres.

Si vous lancer FortiusANT avec -g, l'interface d'utilisateur est ouvert: `FortiusANT.exe -a -g `

regarder le wiki: https://github.com/WouterJD/FortiusANT/wiki#command-line

Succes!

**Comment by regis65** [comment]
Bonjour,
Comment mettons les "arguments facultatif ".
Merci

**Comment by WouterJD** [comment]
Il faux creer un petit fichier FortiusANT.bat
https://github.com/WouterJD/FortiusANT/blob/master/supportfiles/FortiusAnt.bat

avec les regles
```
FortiusAnt.py -g -a
pause

```
et puis on peux executer cette .bat

**Comment by regis65** [comment]
En fait le programme se lance dans bios mais j aimerais avoir l interface
avec les commande du guidon

**Comment by WouterJD** [comment]
Version 3 supportera lancer la programme sans ligne de commande.
Pour ce moment il faux creer un .bat

**Comment by regis65** [comment]
Apres avoir fait le fichier .bat dans quel dossiers faut il l installe .

**Comment by WouterJD** [comment]
Hi @regis65 

Le fichier `FortiusAnt.bat` avec les regles
```
FortiusAnt.py -g -a
pause
```
peut-être installé dans la meme dossier comme les fichier *.py ses mêmes.

Succes!

**Comment by regis65** [comment]
Le fichier .bat je l es installé dans le dossier Pythoncode je lance
fortiusant dans le dossier windowsExecutable et toujours pareil l ecran
bios avec les renseignement du hometrainer avec la vitesse cadence mais je
voudrais installé l interface.
Tres beau programme mais compliqué a installé et paramétré 😢😭
Merci

**Comment by WouterJD** [comment]
I disagree that the program is difficult to install; a bat-file with a commandline should not be complicated.

As said, add the -g flag so that the gui is displayed.

Version 3.0 will be easier to use.

**Comment by regis65** [comment]
je voudrais savoir si sans mettre l interface mon home trainer peux fonctionner parfaitement sous sufferfest, binringvr, zwift, tacx desktop.... ou y aurais t il d autre paramètre a rajoute car je n y arrive pas a faire fonctionner l interface.
merci

**Comment by WouterJD** [comment]
Pour faire le functionner c'est peutetre une idee de demander in Ami avex qc experience avex windows.
Quando ça marche ça marche avec Trainer Road, Zwift, Rouvy, ... tous programmes sopportants ANT FE-C.

**Comment by regis65** [comment]
D'accord merci

**Comment by WouterJD** [comment]
[Version 3.0 is released](https://github.com/WouterJD/FortiusANT/wiki/Version-information#version-30-released-may-19th-2020) and starting the executable should be easier for windows users.
Of course of there are any issues, let me know.

**Comment by regis65** [comment]
Merci mais comment fait on pour le téléchargé Sur le pc

**Comment by WouterJD** [comment]
Vous pouvez remplacer le FortiusANT.exe sur vôtre système avec:
https://github.com/WouterJD/FortiusANT/blob/master/WindowsExecutable/FortiusANT.exe

Le fichier FortiusANT.bat est toujours valable:

```
FortiusAnt.exe
pause
```
suffit; je l'ai fait plus simple - especialement pour vous! :-)

**Comment by regis65** [comment]
Je vous remercie.
Sportivement Régis

**Comment by regis65** [comment]
Salut,
L'Interface fonctionne il n y a plus qu'attendre l arrivée de mes clés Ant+
que j ai commandé sur le net.
Je te tiendrais au courant si sa fonctionne correctement.
Et encore merci bon boulot
Sportivement
Régis

Le mer. 20 mai 2020 à 10:03, Regis Crouzil <regis.crouzil@gmail.com> a
écrit :

> Je vous remercie.
> Sportivement Régis
>

**Comment by WouterJD** [comment]
👍

**Comment by WouterJD** [comment]
No follow-up in two weeks.
If issue needs to be reopened, feel free to do so.

**Comment by regis65** [comment]
Daccord merci,je n es toujours pas reçu les clés ANT+

**Comment by WouterJD** [comment]
Cést bien dommage!
Tu les as commandé deja depuis combien des temps?
En cas je pourrais les commander et envoyer!

**Comment by regis65** [comment]
Vu que j ai commandé en plein confinement,c est normal .
Merci mais je vais attendre sa va pas tardé.
Sportivement
Régis

**Comment by regis65** [comment]
Salut
J ai reçu les clés ANT+ de la marque Anself aujourd'hui quand je lance
explorerAnt sa me marque des erreurs (voir photo ci-joint) mais je lance l
aplication sa fonctionne mais sa se decalibre peux tu m aidé
Merci
Regis

Le lun. 8 juin 2020 à 14:20, Regis Crouzil <regis.crouzil@gmail.com> a
écrit :

> Vu que j ai commandé en plein confinement,c est normal .
> Merci mais je vais attendre sa va pas tardé.
> Sportivement
> Régis
>

**Comment by WouterJD** [comment]
1. Vous n'avez pas besoin de ExplorANT; FortiusANT devrais sufficer.
2. les erreurs je ne vois pas; phot's ne sont pas transferé quand on repond par email (au site github seulement)

Salutr en attendant ta reponse

**Comment by regis65** [comment]
Salut,
En ce moment mon logiciel Fortiusant délire je m ensert sur kinomap et le
résistance des dénivelé fonctionne plus je voudrais connaître le lien du
dernier Fortiusant car le mien c est le 6.2 et je n arrive pas a trouvé le
6.5
Sportivement
Regis

**Comment by MeanHat** [comment]
Salut @regis65 - when I have had similar patterns of uneven resistance it has been caused by the magnet or sensor connected to the Tacx motor/brake unit. No doubt you have already tried this but I thought I would mention it just in case as it is simple to fix.

**Comment by WouterJD** [comment]
==

Salut @ regis65 - lorsque j'ai eu des schémas similaires de résistance inégale, cela a été causé par l'aimant ou le capteur connecté à l'unité moteur/frein Tacx.  Vous avez sans doute déjà essayé cela, mais j'ai pensé que je le mentionnerais au cas où car il est simple à réparer.

**Comment by regis65** [comment]
![20230127_214729](https://user-images.githubusercontent.com/65114605/215218631-63184272-f1c5-4e02-929a-33bbb319bf89.jpg)
Salut,Je t envoie la photo j ai fais ce que tu m as il c est toujours pareil

**Comment by regis65** [comment]
Salut,
J ai téléchargé le fortius ant  6. 64 sur Githu c est toujours pareil j
arrive pas a trouvé la panne pour simulé les dénivelé.
Je t envoi la photo.
Sportivement Regis
