### ISSUE TITLE
Probleme ANT+

### ISSUE THREAD

**Issue by regis65** [WouterJD/FortiusANT#97]
Salut
J ai reçu les clés ANT+ de la marque Anself aujourd'hui quand je lance explorerAnt sa me marque des erreurs (voir photo ci-joint) mais je lance l aplication sa fonctionne mais sa se decalibre peux tu m aidé
Merci
Regis
![20200615_183001](https://user-images.githubusercontent.com/65114605/84701447-4ef54800-af55-11ea-961e-b90d3a397cca.jpg)

**Comment by WouterJD** [comment]
quel versione del FortiusANT?Photo de lecran svp
    	
    	

    	Met vriendelijke groeten Wouter Dubbeldam
    
  




On Mon, Jun 15, 2020 at 10:13 PM +0200, "regis65" <notifications@github.com> wrote:
















Salut


J ai reçu les clés ANT+ de la marque Anself aujourd'hui quand je lance explorerAnt sa me marque des erreurs (voir photo ci-joint) mais je lance l aplication sa fonctionne mais sa se decalibre peux tu m aidé


Merci


Regis

**Comment by regis65** [comment]
La version c est celle du 18.9 2019.
Sportivement
Regis

**Comment by WouterJD** [comment]
En settembre 2019, FortiusANT n'existait pas...
S'il vous plais utilisez version 3.2 parce que c'est la version plus courant

**Comment by regis65** [comment]
Merci mais je ne l es trouvé
FortiusAnt 3.2
Sportivement
Regis

**Comment by WouterJD** [comment]
c'est au github
https://github.com/WouterJD/FortiusANT/

**Comment by regis65** [comment]
Salut j ai téléchargement fortiusant 3.2 mais j ai toujours une erreur(voir photo)
![20200617_102610](https://user-images.githubusercontent.com/65114605/84876915-1d30ce00-b088-11ea-902f-47cb971755fa.jpg)
 et zwift ne reconnait pas l home trainer

**Comment by WouterJD** [comment]
Excuse-moi Beaucoup
J'ai trouvé Vette erreur hier, je publierai 3.2.1 leuk plus vite possibile. Je te fais savoir aujourd'hui

**Comment by regis65** [comment]
Je te remercie, mais sans urge pas à la minute.
Sportivement
Régis

**Comment by WouterJD** [comment]
Merci, mais c'est fait.
Hier j'avais déja solué la problème; maintenant c'etait seulement pousser qq boutons

A plus tard!

**Comment by regis65** [comment]
Ok je vais attendre que tu le mettes en ligne.
Sportivement
Regis

**Comment by regis65** [comment]
Quand tu l auras mis en ligne tiens moi au courant.
Merci
Regis

Le mer. 17 juin 2020 à 13:36, Regis Crouzil <regis.crouzil@gmail.com> a
écrit :

**Comment by WouterJD** [comment]
Deja fait a 11h ce matin

**Comment by regis65** [comment]
Salut j ai essayé ta nouvelle version (3.2.1) sa fonctionne sur Zwift .
Merci
Sportivement
Régis

**Comment by WouterJD** [comment]
Top!

**Comment by regis65** [comment]
Salut,
Je possede le FortiusAnt depuis le mois de juin 2020 je voudrais y a t il
une nouvelle version.
Merci

**Comment by WouterJD** [comment]
Regis bonjour. Ils sont des petits modifications, pas des dévélopments nouvelles.
Est-ce-que tu as des idees, desires?

**Comment by regis65** [comment]
Salut, c etait juste pour savoir
Et merci encore d avoir fait cette application,sa m embêté d acheter un
autre home trainer.
Sportivement
Régis.Crouzil

**Comment by regis65** [comment]
Salut dis moi as tu l intention de voir si on pourra le faire fonctionné en
Bluetooth un jour?
Cordialement
Regis

Le dim. 18 oct. 2020 à 09:40, Regis Crouzil <regis.crouzil@gmail.com> a
écrit :

**Comment by WouterJD** [comment]
Voyez #103; en effet non. Si il-y-a qc qui le fsir, je veux vien intégrer. Mais la development coûtera des temps et ne me porterá rien; et les utilisants futur seulement l'avantage de ne pas devoir acheter les deux dongles.
Je crois que la connection au telefone n'est pas une vrai avantage pour une zwifter.

**Comment by regis65** [comment]
Daccord merci pour ta réponse.
