### ISSUE TITLE
Compatibility with TTS4?

### ISSUE THREAD

**Issue by EvoxRider365** [WouterJD/FortiusANT#98]
I have Fortius T1932.  I have TTS4 running on Windows 10.  Can FortiusANT and TTS4 run on the same computer?  I would like to use both if possible.  Please respond.  Thanks

**Comment by EvoxRider365** [comment]
Or in other words, can TTS4 and FortiusANT coexist?  I would run them separately but I would like to still use TTS4 for as long as I can.

**Comment by WouterJD** [comment]
Save as #99 and since more info there, I close this isse

**Comment by EvoxRider365** [comment]
Sorry I had a busy busy week and only attempted installation last night.  
Re: installation
Windows 10 Home 65 bit
I could see my TACX Ant antenna and the Garmin ANT+ USB2 dongle that I purchased used last weekend.
I created .inf files for each but they would not install. "Error installing Driver - System policy has been modified to reject unsigned drivers."

libusb-win32 device filter installed successfully
I was able to install device filters for both ANT USB antennas.
I was not able to connect to the TACX Fortius however so I went back and installed the VR Interface as well (following the suggestion of installation option 2 for fortius ant)
I was then able to run and calibrate the Fortius Ant 3.2.1 application while connected to T1932

I was able to connect to Strava (I think)
I was more interested in getting Zwift up and running.
I started the installation but it took a long time to download and install the app.

The app can see the trainer but the trainer is not moving the rider on the screen.  When I push buttons on the Tacx head unit I sometimes move a metre or two on the screen but then it stops again.  

Sometimes the Zwift menu popped on and off the screen erratically with a prompt to end my ride to nowhere....

There are no watts showing in the upper right hand corner, no speed, etc.  

Meanwhile the pedalling I did to get started resulted in the motor spinning the wheel forever.

Any suggestions at this point?  Maybe I will try the earlier version of Fortius ant and check my usb cable from the Fortius to my computer.

I am also going to see if TTS4 will still run.

Suggestions welcome...hoping this will work...

**Comment by regis65** [comment]
Bonjour,
Depuis que j ai installé FortiusAnt sur un autre pc ,
Il ne reconnait plus l interface de mon home trainer Forius en le branchant en usb,
Pouvez vous m aidé 
Sportivement
 Régis

**Comment by WouterJD** [comment]
Bonjour Régis!

Si vous me racconter un peux plus, peut-etre je peux aider - bien sur.

**Comment by regis65** [comment]
salut en fait sur mon pc j' ai fortius ant et Tacx Trainer Software pour
mon home trainer Fortius mais malheureusement quand je lance Tacx Trainer
je n est plus l interface qui fonctionne le vr et le moteur.
sportive
ment
regis

Le lun. 30 nov. 2020 à 08:17, Wouter Dubbeldam <notifications@github.com> a
écrit :

**Comment by WouterJD** [comment]
Regis, TTS and FortiusANT do not necessarily work together on the same system.

**Comment by regis65** [comment]
Ok merci, je pensais que les 2 programmes pouvais fonctionné sur le meme pc.
Tant pis
Sportivement
Régis

Le mer. 2 déc. 2020 à 00:21, Wouter Dubbeldam <notifications@github.com> a
écrit :

**Comment by regis65** [comment]
Salut,
Déjà meilleurs voeux 2021 pour toi et ta famille
Dis moi hier j ai casse le cable du capteur de cadence  de mon Fortius et
je cherche un site qui vendrais des pieces détaché de home trainer et je
voudrais savoir si tu en connait un.
Merci
Regis

Le mer. 2 déc. 2020 à 07:05, Regis Crouzil <regis.crouzil@gmail.com> a
écrit :
